import type { User, Ticket, Solution, SystemNode, Alert } from '@/types'

export const mockUser: User = {
  id: 'u1',
  name: 'Alex Reeves',
  email: 'alex@company.com',
  role: 'admin',
  xp: 1340,
  level: 5,
  badge: '🔧',
  ticketsResolved: 47,
  solutionsAdded: 12,
}

export const mockUsers: User[] = [
  { id: 'u1', name: 'Alex Reeves', email: 'alex@company.com', role: 'admin', xp: 1340, level: 5, badge: '🔧', ticketsResolved: 47, solutionsAdded: 12 },
  { id: 'u2', name: 'Sara Mendez', email: 'sara@company.com', role: 'it_master', xp: 3850, level: 8, badge: '🔐', ticketsResolved: 124, solutionsAdded: 38 },
  { id: 'u3', name: 'Jake Torres', email: 'jake@company.com', role: 'user', xp: 420, level: 3, badge: '🛠️', ticketsResolved: 9, solutionsAdded: 2 },
  { id: 'u4', name: 'Priya Nair', email: 'priya@company.com', role: 'admin', xp: 2100, level: 7, badge: '⚔️', ticketsResolved: 76, solutionsAdded: 21 },
  { id: 'u5', name: 'Omar Hassan', email: 'omar@company.com', role: 'user', xp: 680, level: 4, badge: '💻', ticketsResolved: 18, solutionsAdded: 5 },
]

export const mockSolutions: Solution[] = [
  {
    id: 's1',
    title: 'Fix Slow PC / High CPU Usage',
    description: 'Step-by-step guide to resolve slow computer performance.',
    steps: [
      'Open Task Manager (Ctrl+Shift+Esc) and check CPU/Memory usage',
      'Disable unnecessary startup programs: Settings → Apps → Startup',
      'Run Disk Cleanup: Search "Disk Cleanup" → select C: drive',
      'Clear browser cache and temp files (%temp% in Run)',
      'Run Windows Defender full scan for malware',
      'Check for Windows Updates and install pending ones',
      'Restart the computer and monitor performance',
    ],
    tags: ['performance', 'slow', 'cpu', 'memory', 'startup'],
    category: 'hardware',
    successRate: 87,
    usageCount: 342,
    addedBy: 'Sara Mendez',
    createdAt: '2026-01-15',
  },
  {
    id: 's2',
    title: 'WiFi Not Connecting / No Internet',
    description: 'Diagnose and fix wireless network connectivity issues.',
    steps: [
      'Toggle Airplane Mode off/on via system tray',
      'Right-click WiFi icon → Troubleshoot problems',
      'Forget and reconnect to your network',
      'Flush DNS: Open CMD as Admin → run "ipconfig /flushdns"',
      'Reset TCP/IP: CMD as Admin → "netsh int ip reset"',
      'Update network adapter driver in Device Manager',
      'Check router — restart it if needed',
    ],
    tags: ['wifi', 'internet', 'network', 'connectivity', 'dns'],
    category: 'network',
    successRate: 91,
    usageCount: 512,
    addedBy: 'Alex Reeves',
    createdAt: '2026-01-20',
  },
  {
    id: 's3',
    title: 'Printer Not Found / Offline',
    description: 'Resolve printer detection and offline status errors.',
    steps: [
      'Check all cable connections and power the printer off/on',
      'Set printer as default: Settings → Bluetooth & devices → Printers',
      'Remove and re-add the printer from Windows settings',
      'Clear print queue: Services → Print Spooler → Stop → clear folder → Start',
      'Download latest driver from manufacturer website',
      'Try printing from a different application',
    ],
    tags: ['printer', 'offline', 'driver', 'print queue'],
    category: 'hardware',
    successRate: 78,
    usageCount: 189,
    addedBy: 'Jake Torres',
    createdAt: '2026-02-01',
  },
  {
    id: 's4',
    title: 'Outlook Not Receiving Emails',
    description: 'Troubleshoot Microsoft Outlook email sync issues.',
    steps: [
      'Check internet connection is working',
      'Verify account settings: File → Account Settings',
      'Run Microsoft Support and Recovery Assistant (SaRA)',
      'Disable Cached Exchange Mode temporarily and re-enable',
      'Repair Office installation: Control Panel → Programs → Repair',
      'Create new Outlook profile if issue persists',
    ],
    tags: ['outlook', 'email', 'microsoft', 'exchange', 'sync'],
    category: 'software',
    successRate: 83,
    usageCount: 276,
    addedBy: 'Priya Nair',
    createdAt: '2026-02-10',
  },
  {
    id: 's5',
    title: 'Blue Screen of Death (BSOD)',
    description: 'Diagnose and fix Windows Blue Screen errors.',
    steps: [
      'Note the stop code shown on the BSOD screen',
      'Boot into Safe Mode: Hold Shift + Restart → Troubleshoot → Advanced Options',
      'Run System File Checker: CMD as Admin → "sfc /scannow"',
      'Run DISM: "DISM /Online /Cleanup-Image /RestoreHealth"',
      'Check RAM: Run Windows Memory Diagnostic',
      'Update or roll back recently installed drivers',
      'Check Event Viewer for critical errors around the crash time',
    ],
    tags: ['bsod', 'crash', 'blue screen', 'windows', 'driver'],
    category: 'hardware',
    successRate: 72,
    usageCount: 134,
    addedBy: 'Sara Mendez',
    createdAt: '2026-02-15',
  },
  {
    id: 's6',
    title: 'VPN Connection Failed',
    description: 'Fix common VPN connectivity and authentication errors.',
    steps: [
      'Verify VPN credentials are correct',
      'Check if VPN server address is reachable (ping test)',
      'Disable firewall temporarily to test connectivity',
      'Update VPN client to latest version',
      'Try different VPN protocol (IKEv2 vs OpenVPN vs L2TP)',
      'Check Windows Firewall is not blocking the VPN ports',
      'Contact IT admin if MFA token has expired',
    ],
    tags: ['vpn', 'remote', 'connection', 'authentication', 'network'],
    category: 'network',
    successRate: 80,
    usageCount: 98,
    addedBy: 'Omar Hassan',
    createdAt: '2026-03-01',
  },
  {
    id: 's7',
    title: 'Microsoft 365 Login Issues',
    description: 'Resolve sign-in and MFA problems with Microsoft 365.',
    steps: [
      'Clear browser cookies and cache, then retry',
      'Try signing in from a private/incognito browser window',
      'Check Microsoft 365 service health at admin.microsoft.com',
      'Re-register MFA: Go to aka.ms/mfasetup',
      'Sign out of all Microsoft accounts and sign back in',
      'Check if account is licensed: Microsoft 365 Admin Center → Users',
      'Contact IT admin if account is disabled or expired',
    ],
    tags: ['microsoft 365', 'office', 'login', 'mfa', 'azure ad'],
    category: 'software',
    successRate: 88,
    usageCount: 410,
    addedBy: 'Alex Reeves',
    createdAt: '2026-03-05',
  },
  {
    id: 's8',
    title: 'Disk Space Running Low',
    description: 'Free up disk space and manage storage efficiently.',
    steps: [
      'Run Storage Sense: Settings → System → Storage → Turn on Storage Sense',
      'Remove unused apps: Settings → Apps → Sort by size',
      'Empty Recycle Bin and Downloads folder',
      'Move files to OneDrive or external storage',
      'Use WinDirStat to identify large files',
      'Disable hibernation if not needed: CMD → "powercfg /h off"',
      'Clean Windows.old folder if available',
    ],
    tags: ['disk', 'storage', 'space', 'cleanup', 'full'],
    category: 'hardware',
    successRate: 94,
    usageCount: 267,
    addedBy: 'Priya Nair',
    createdAt: '2026-03-10',
  },
]

export const mockTickets: Ticket[] = [
  {
    id: 't1',
    title: 'WiFi dropping every 30 minutes',
    description: 'My connection keeps dropping exactly every 30 min. Reconnects after 2-3 min.',
    priority: 'high',
    status: 'in_progress',
    category: 'network',
    userId: 'u3',
    userName: 'Jake Torres',
    assignedTo: 'Alex Reeves',
    createdAt: '2026-05-29T08:00:00Z',
    updatedAt: '2026-05-29T10:30:00Z',
    solutionsTried: ['s2'],
  },
  {
    id: 't2',
    title: 'Outlook keeps crashing on startup',
    description: 'Office 365 Outlook crashes immediately after the loading screen.',
    priority: 'critical',
    status: 'open',
    category: 'software',
    userId: 'u5',
    userName: 'Omar Hassan',
    createdAt: '2026-05-30T07:15:00Z',
    updatedAt: '2026-05-30T07:15:00Z',
    solutionsTried: [],
  },
  {
    id: 't3',
    title: 'Printer showing as offline in Finance dept',
    description: 'HP LaserJet in Finance not printing. Showing offline for 3 users.',
    priority: 'medium',
    status: 'open',
    category: 'hardware',
    userId: 'u1',
    userName: 'Alex Reeves',
    createdAt: '2026-05-30T09:00:00Z',
    updatedAt: '2026-05-30T09:00:00Z',
    solutionsTried: ['s3'],
  },
  {
    id: 't4',
    title: 'VPN not connecting for remote work',
    description: 'Error 789: L2TP connection attempt failed.',
    priority: 'high',
    status: 'resolved',
    category: 'network',
    userId: 'u5',
    userName: 'Omar Hassan',
    assignedTo: 'Sara Mendez',
    createdAt: '2026-05-28T14:00:00Z',
    updatedAt: '2026-05-29T11:00:00Z',
    solutionsTried: ['s6'],
  },
  {
    id: 't5',
    title: 'PC extremely slow after Windows update',
    description: 'After KB5034441 update, boot takes 8+ minutes and apps lag badly.',
    priority: 'high',
    status: 'in_progress',
    category: 'hardware',
    userId: 'u3',
    userName: 'Jake Torres',
    assignedTo: 'Priya Nair',
    createdAt: '2026-05-29T15:00:00Z',
    updatedAt: '2026-05-30T08:00:00Z',
    solutionsTried: ['s1'],
  },
  {
    id: 't6',
    title: 'Microsoft 365 MFA not working',
    description: "Getting 'your sign-in was blocked' for the entire sales team.",
    priority: 'critical',
    status: 'in_progress',
    category: 'software',
    userId: 'u4',
    userName: 'Priya Nair',
    assignedTo: 'Sara Mendez',
    createdAt: '2026-05-30T06:30:00Z',
    updatedAt: '2026-05-30T09:45:00Z',
    solutionsTried: ['s7'],
  },
]

export const mockNodes: SystemNode[] = [
  { id: 'n1', name: 'CORE-DC-01', type: 'server', status: 'healthy', cpu: 34, memory: 62, disk: 41, uptime: '187d', alerts: 0, x: 50, y: 50 },
  { id: 'n2', name: 'CORE-DC-02', type: 'server', status: 'warning', cpu: 78, memory: 85, disk: 55, uptime: '187d', alerts: 2, x: 75, y: 30 },
  { id: 'n3', name: 'FILE-SRV-01', type: 'storage', status: 'healthy', cpu: 22, memory: 44, disk: 88, uptime: '90d', alerts: 1, x: 25, y: 30 },
  { id: 'n4', name: 'NET-SW-CORE', type: 'network', status: 'healthy', cpu: 12, memory: 31, disk: 10, uptime: '365d', alerts: 0, x: 50, y: 20 },
  { id: 'n5', name: 'AZURE-VM-01', type: 'cloud', status: 'healthy', cpu: 45, memory: 58, disk: 62, uptime: '45d', alerts: 0, x: 80, y: 60 },
  { id: 'n6', name: 'APP-SRV-WEB', type: 'server', status: 'critical', cpu: 96, memory: 94, disk: 72, uptime: '23d', alerts: 5, x: 20, y: 65 },
  { id: 'n7', name: 'WS-FINANCE-01', type: 'workstation', status: 'warning', cpu: 55, memory: 71, disk: 91, uptime: '12d', alerts: 3, x: 60, y: 75 },
  { id: 'n8', name: 'BACKUP-NAS-01', type: 'storage', status: 'offline', cpu: 0, memory: 0, disk: 0, uptime: '0d', alerts: 1, x: 35, y: 75 },
]

export const mockAlerts: Alert[] = [
  { id: 'a1', nodeId: 'n6', nodeName: 'APP-SRV-WEB', message: 'CPU usage at 96% for 15+ minutes', severity: 'critical', timestamp: '2026-05-30T09:50:00Z', acknowledged: false },
  { id: 'a2', nodeId: 'n2', nodeName: 'CORE-DC-02', message: 'Memory usage exceeded 85%', severity: 'warning', timestamp: '2026-05-30T09:30:00Z', acknowledged: false },
  { id: 'a3', nodeId: 'n7', nodeName: 'WS-FINANCE-01', message: 'Disk usage at 91% — low space', severity: 'warning', timestamp: '2026-05-30T08:15:00Z', acknowledged: false },
  { id: 'a4', nodeId: 'n8', nodeName: 'BACKUP-NAS-01', message: 'Node unreachable — possible hardware failure', severity: 'critical', timestamp: '2026-05-30T07:00:00Z', acknowledged: true },
  { id: 'a5', nodeId: 'n3', nodeName: 'FILE-SRV-01', message: 'Disk usage approaching threshold (88%)', severity: 'warning', timestamp: '2026-05-30T06:45:00Z', acknowledged: true },
]
