import type { User, Ticket, Solution, SystemNode, Alert } from '@/types'

export const mockUser: User = {
  id: 'u1',
  name: 'Alex Reeves',
  email: 'alex@company.com',
  role: 'admin',
  xp: 1340,
  level: 5,
  badge: '🔧',
  ticketsResolved: 47,
  solutionsAdded: 12,
}

export const mockUsers: User[] = [
  { id: 'u1', name: 'Alex Reeves', email: 'alex@company.com', role: 'admin', xp: 1340, level: 5, badge: '🔧', ticketsResolved: 47, solutionsAdded: 12 },
  { id: 'u2', name: 'Sara Mendez', email: 'sara@company.com', role: 'it_master', xp: 3850, level: 8, badge: '🔐', ticketsResolved: 124, solutionsAdded: 38 },
  { id: 'u3', name: 'Jake Torres', email: 'jake@company.com', role: 'user', xp: 420, level: 3, badge: '🛠️', ticketsResolved: 9, solutionsAdded: 2 },
  { id: 'u4', name: 'Priya Nair', email: 'priya@company.com', role: 'admin', xp: 2100, level: 7, badge: '⚔️', ticketsResolved: 76, solutionsAdded: 21 },
  { id: 'u5', name: 'Omar Hassan', email: 'omar@company.com', role: 'user', xp: 680, level: 4, badge: '💻', ticketsResolved: 18, solutionsAdded: 5 },
]

export const mockSolutions: Solution[] = [
  {
    id: 's1',
    title: 'Fix Slow PC / High CPU Usage',
    description: 'Step-by-step guide to resolve slow computer performance.',
    steps: [
      'Open Task Manager (Ctrl+Shift+Esc) and check CPU/Memory usage',
      'Disable unnecessary startup programs: Settings → Apps → Startup',
      'Run Disk Cleanup: Search "Disk Cleanup" → select C: drive',
      'Clear browser cache and temp files (%temp% in Run)',
      'Run Windows Defender full scan for malware',
      'Check for Windows Updates and install pending ones',
      'Restart the computer and monitor performance',
    ],
    tags: ['performance', 'slow', 'cpu', 'memory', 'startup'],
    category: 'hardware',
    successRate: 87,
    usageCount: 342,
    addedBy: 'Sara Mendez',
    createdAt: '2026-01-15',
  },
  {
    id: 's2',
    title: 'WiFi Not Connecting / No Internet',
    description: 'Diagnose and fix wireless network connectivity issues.',
    steps: [
      'Toggle Airplane Mode off/on via system tray',
      'Right-click WiFi icon → Troubleshoot problems',
      'Forget and reconnect to your network',
      'Flush DNS: Open CMD as Admin → run "ipconfig /flushdns"',
      'Reset TCP/IP: CMD as Admin → "netsh int ip reset"',
      'Update network adapter driver in Device Manager',
      'Check router — restart it if needed',
    ],
    tags: ['wifi', 'internet', 'network', 'connectivity', 'dns'],
    category: 'network',
    successRate: 91,
    usageCount: 512,
    addedBy: 'Alex Reeves',
    createdAt: '2026-01-20',
  },
  {
    id: 's3',
    title: 'Printer Not Found / Offline',
    description: 'Resolve printer detection and offline status errors.',
    steps: [
      'Check all cable connections and power the printer off/on',
      'Set printer as default: Settings → Bluetooth & devices → Printers',
      'Remove and re-add the printer from Windows settings',
      'Clear print queue: Services → Print Spooler → Stop → clear folder → Start',
      'Download latest driver from manufacturer website',
      'Try printing from a different application',
    ],
    tags: ['printer', 'offline', 'driver', 'print queue'],
    category: 'hardware',
    successRate: 78,
    usageCount: 189,
    addedBy: 'Jake Torres',
    createdAt: '2026-02-01',
  },
  {
    id: 's4',
    title: 'Outlook Not Receiving Emails',
    description: 'Troubleshoot Microsoft Outlook email sync issues.',
    steps: [
      'Check internet connection is working',
      'Verify account settings: File → Account Settings',
      'Run Microsoft Support and Recovery Assistant (SaRA)',
      'Disable Cached Exchange Mode temporarily and re-enable',
      'Repair Office installation: Control Panel → Programs → Repair',
      'Create new Outlook profile if issue persists',
    ],
    tags: ['outlook', 'email', 'microsoft', 'exchange', 'sync'],
    category: 'software',
    successRate: 83,
    usageCount: 276,
    addedBy: 'Priya Nair',
    createdAt: '2026-02-10',
  },
  {
    id: 's5',
    title: 'Blue Screen of Death (BSOD)',
    description: 'Diagnose and fix Windows Blue Screen errors.',
    steps: [
      'Note the stop code shown on the BSOD screen',
      'Boot into Safe Mode: Hold Shift + Restart → Troubleshoot → Advanced Options',
      'Run System File Checker: CMD as Admin → "sfc /scannow"',
      'Run DISM: "DISM /Online /Cleanup-Image /RestoreHealth"',
      'Check RAM: Run Windows Memory Diagnostic',
      'Update or roll back recently installed drivers',
      'Check Event Viewer for critical errors around the crash time',
    ],
    tags: ['bsod', 'crash', 'blue screen', 'windows', 'driver'],
    category: 'hardware',
    successRate: 72,
    usageCount: 134,
    addedBy: 'Sara Mendez',
    createdAt: '2026-02-15',
  },
  {
    id: 's6',
    title: 'VPN Connection Failed',
    description: 'Fix common VPN connectivity and authentication errors.',
    steps: [
      'Verify VPN credentials are correct',
      'Check if VPN server address is reachable (ping test)',
      'Disable firewall temporarily to test connectivity',
      'Update VPN client to latest version',
      'Try different VPN protocol (IKEv2 vs OpenVPN vs L2TP)',
      'Check Windows Firewall is not blocking the VPN ports',
      'Contact IT admin if MFA token has expired',
    ],
    tags: ['vpn', 'remote', 'connection', 'authentication', 'network'],
    category: 'network',
    successRate: 80,
    usageCount: 98,
    addedBy: 'Omar Hassan',
    createdAt: '2026-03-01',
  },
  {
    id: 's7',
    title: 'Microsoft 365 Login Issues',
    description: 'Resolve sign-in and MFA problems with Microsoft 365.',
    steps: [
      'Clear browser cookies and cache, then retry',
      'Try signing in from a private/incognito browser window',
      'Check Microsoft 365 service health at admin.microsoft.com',
      'Re-register MFA: Go to aka.ms/mfasetup',
      'Sign out of all Microsoft accounts and sign back in',
      'Check if account is licensed: Microsoft 365 Admin Center → Users',
      'Contact IT admin if account is disabled or expired',
    ],
    tags: ['microsoft 365', 'office', 'login', 'mfa', 'azure ad'],
    category: 'software',
    successRate: 88,
    usageCount: 410,
    addedBy: 'Alex Reeves',
    createdAt: '2026-03-05',
  },
  {
    id: 's8',
    title: 'Disk Space Running Low',
    description: 'Free up disk space and manage storage efficiently.',
    steps: [
      'Run Storage Sense: Settings → System → Storage → Turn on Storage Sense',
      'Remove unused apps: Settings → Apps → Sort by size',
      'Empty Recycle Bin and Downloads folder',
      'Move files to OneDrive or external storage',
      'Use WinDirStat to identify large files',
      'Disable hibernation if not needed: CMD → "powercfg /h off"',
      'Clean Windows.old folder if available',
    ],
    tags: ['disk', 'storage', 'space', 'cleanup', 'full'],
    category: 'hardware',
    successRate: 94,
    usageCount: 267,
    addedBy: 'Priya Nair',
    createdAt: '2026-03-10',
  },

  // ── Batch 2: Additional IT Solutions ─────────────────────────────────────────

  {
    id: 's9',
    title: 'Active Directory Account Locked Out',
    description: 'Unlock and troubleshoot an AD account that has been locked due to failed login attempts.',
    steps: [
      'Ask user to wait 30 minutes — AD auto-unlock policy may resolve it',
      'IT Admin: Open Active Directory Users & Computers (ADUC)',
      'Find the user account → right-click → Properties → Account tab',
      'Uncheck "Unlock account" checkbox and click Apply → OK',
      'Check Event Viewer on Domain Controller: Security log → Event ID 4740 (account lockout)',
      'Identify the lockout source: run "Get-ADUser username -Properties * | Select LockedOut, PasswordExpired, BadLogonCount"',
      'Reset password if needed: right-click account → Reset Password',
      'Advise user to check all devices (phone, tablet) for saved old credentials',
    ],
    tags: ['active directory', 'account locked', 'ad', 'lockout', 'domain', 'password'],
    category: 'identity',
    successRate: 96,
    usageCount: 312,
    addedBy: 'Sara Mendez',
    createdAt: '2026-03-15',
  },
  {
    id: 's10',
    title: 'Mapped Network Drive Disconnecting / Not Available',
    description: 'Fix mapped drives that disconnect after restart or show as unavailable (red X).',
    steps: [
      'Check if the file server is reachable: ping \\\\servername',
      'Re-map the drive manually: This PC → Map network drive → enter \\\\server\\share',
      'Check "Reconnect at sign-in" box when mapping',
      'In Registry: HKLM\\System\\CurrentControlSet\\Control\\NetworkProvider → set "RestoreConnection" to 1',
      'Open Services → set "Workstation" and "TCP/IP NetBIOS Helper" to Automatic',
      'Run: net use * /persistent:yes in CMD',
      'If VPN-dependent: ensure VPN connects before drive mapping scripts run',
      'GPO fix (IT admin): Computer Configuration → Windows Settings → Drive Maps → Update action',
    ],
    tags: ['mapped drive', 'network share', 'drive disconnecting', 'smb', 'file server'],
    category: 'network',
    successRate: 81,
    usageCount: 178,
    addedBy: 'Alex Reeves',
    createdAt: '2026-03-20',
  },
  {
    id: 's11',
    title: 'Remote Desktop (RDP) Connection Failed',
    description: 'Troubleshoot RDP "Cannot connect to the remote computer" errors.',
    steps: [
      'Verify the target PC is powered on and connected to the network',
      'Ping the remote IP: ping 192.168.x.x',
      'Check RDP is enabled: Settings → System → Remote Desktop → turn on',
      'Check firewall: Windows Firewall → Allow Remote Desktop rule (port 3389)',
      'Check if user has RDP permissions: System Properties → Remote tab → Select Users',
      'Try connecting via IP address instead of hostname (DNS issue possible)',
      'Check NLA setting: if you see "CredSSP encryption oracle" error, apply KB4093492 patch',
      'Verify Remote Desktop Services is running: services.msc → check status',
    ],
    tags: ['rdp', 'remote desktop', 'cannot connect', 'remote access', '3389'],
    category: 'network',
    successRate: 85,
    usageCount: 234,
    addedBy: 'Priya Nair',
    createdAt: '2026-03-25',
  },
  {
    id: 's12',
    title: 'Microsoft Teams Not Loading / Stuck on Splash Screen',
    description: 'Fix Teams stuck on loading screen, white screen, or constant reconnecting.',
    steps: [
      'Close Teams completely: right-click system tray → Quit',
      'Clear Teams cache: %appdata%\\Microsoft\\Teams → delete contents of "Cache", "GPUCache", "databases", "Local Storage" folders',
      'Restart Teams and sign in again',
      'If still stuck: uninstall and reinstall Teams (download from teams.microsoft.com)',
      'Try Teams Web App in browser (teams.microsoft.com) to isolate desktop vs. account issue',
      'Check Microsoft 365 service health at admin.microsoft.com → Service Health',
      'Disable hardware acceleration: Teams → Settings → General → uncheck "Disable GPU hardware acceleration"',
      'If new Teams: Settings → About → switch to "New Teams" toggle off/on',
    ],
    tags: ['teams', 'microsoft teams', 'not loading', 'stuck', 'cache', 'white screen'],
    category: 'software',
    successRate: 88,
    usageCount: 445,
    addedBy: 'Omar Hassan',
    createdAt: '2026-04-01',
  },
  {
    id: 's13',
    title: 'OneDrive Sync Issues / Files Not Syncing',
    description: 'Resolve OneDrive sync errors, paused sync, and files stuck in processing.',
    steps: [
      'Check sync status icon in system tray — hover to see error message',
      'Click OneDrive icon → Help & Settings → View sync problems',
      'Pause and resume sync: OneDrive settings → Pause syncing → Resume syncing',
      'Check available disk space — OneDrive requires free local space to sync',
      'Check file/folder name for special characters: < > : " / \\ | ? * are not allowed',
      'Reset OneDrive: Win+R → type: "C:\\Program Files\\Microsoft OneDrive\\onedrive.exe /reset" → run',
      'Sign out and sign back in to OneDrive',
      'For SharePoint library sync issues: Unlink site → re-sync from browser',
    ],
    tags: ['onedrive', 'sync', 'not syncing', 'files', 'sharepoint', 'upload'],
    category: 'software',
    successRate: 82,
    usageCount: 287,
    addedBy: 'Jake Torres',
    createdAt: '2026-04-05',
  },
  {
    id: 's14',
    title: 'Windows Update Stuck / Failing to Install',
    description: 'Fix Windows Update errors, stuck at 0%, or update rollback loops.',
    steps: [
      'Run Windows Update Troubleshooter: Settings → Update & Security → Troubleshoot → Windows Update',
      'Stop Windows Update service: CMD as admin → "net stop wuauserv" then "net stop bits"',
      'Clear update cache: delete contents of C:\\Windows\\SoftwareDistribution\\Download',
      'Restart services: "net start wuauserv" and "net start bits"',
      'Run: "sfc /scannow" and "DISM /Online /Cleanup-Image /RestoreHealth"',
      'Check Windows Update log: Event Viewer → Windows Logs → System (filter for WindowsUpdateClient)',
      'For error 0x80070422: set Windows Update service to Automatic startup',
      'If update fails repeatedly: use Windows Update Media Creation Tool for in-place upgrade',
    ],
    tags: ['windows update', 'update failed', 'stuck', 'error', '0x80070422', 'kb update'],
    category: 'software',
    successRate: 74,
    usageCount: 321,
    addedBy: 'Sara Mendez',
    createdAt: '2026-04-10',
  },
  {
    id: 's15',
    title: 'USB Device Not Recognized',
    description: 'Fix "USB device not recognized" errors and devices not showing up.',
    steps: [
      'Try a different USB port (preferably USB 3.0 blue port for newer devices)',
      'Try the device on another PC to rule out hardware failure',
      'Unplug and replug the device — check Device Manager for "Unknown Device"',
      'Update USB hub/controller driver: Device Manager → Universal Serial Bus controllers → Update driver',
      'Disable USB selective suspend: Power Options → Change plan settings → Advanced → USB settings → set to Disabled',
      'Open CMD as admin → run: "net localgroup" (check USB policy)',
      'Run hardware troubleshooter: Settings → Update & Security → Troubleshoot → Hardware and Devices',
      'For USB drives: Disk Management → check if drive shows but has no letter → Assign drive letter',
    ],
    tags: ['usb', 'device not recognized', 'usb port', 'peripheral', 'flash drive'],
    category: 'hardware',
    successRate: 79,
    usageCount: 198,
    addedBy: 'Alex Reeves',
    createdAt: '2026-04-15',
  },
  {
    id: 's16',
    title: 'No Sound / Audio Not Working',
    description: 'Diagnose and fix Windows sound issues including no audio output.',
    steps: [
      'Check volume mixer: right-click speaker icon → Open Volume Mixer — unmute all apps',
      'Check default playback device: right-click speaker icon → Sounds → Playback tab → set correct device as Default',
      'Run Audio Troubleshooter: Settings → Update & Security → Troubleshoot → Playing Audio',
      'Restart Windows Audio service: services.msc → Windows Audio → Restart',
      'Update audio driver: Device Manager → Sound, video and game controllers → right-click → Update driver',
      'If Realtek: download latest driver from Realtek website or PC manufacturer',
      'Check HDMI audio: if using HDMI monitor, set it as default playback device',
      'For headset: check headset jack is fully plugged in and audio jack selector popup appeared',
    ],
    tags: ['audio', 'sound', 'no sound', 'speaker', 'headset', 'volume', 'realtek'],
    category: 'hardware',
    successRate: 86,
    usageCount: 203,
    addedBy: 'Jake Torres',
    createdAt: '2026-04-18',
  },
  {
    id: 's17',
    title: 'Webcam Not Detected / Camera Not Working',
    description: 'Fix camera not detected in Teams, Zoom, or Windows Camera app.',
    steps: [
      'Check physical: external cameras need to be plugged in and powered',
      'Check privacy settings: Settings → Privacy → Camera → ensure apps are allowed to access camera',
      'Check Device Manager: Imaging Devices or Cameras → look for yellow warning icon',
      'Enable camera in Device Manager if disabled: right-click → Enable device',
      'Update camera driver: right-click → Update driver → Search automatically',
      'Test with Windows Camera app (search "Camera") to isolate to specific app vs. driver',
      'For built-in laptop camera: check if physical camera disable switch/key exists (Fn+F key)',
      'In Teams/Zoom: Settings → Devices → ensure correct camera is selected',
    ],
    tags: ['webcam', 'camera', 'teams camera', 'not detected', 'video call'],
    category: 'hardware',
    successRate: 83,
    usageCount: 156,
    addedBy: 'Omar Hassan',
    createdAt: '2026-04-20',
  },
  {
    id: 's18',
    title: 'Screen Flickering / Display Issues',
    description: 'Fix monitor flickering, black screen flashes, or display going off periodically.',
    steps: [
      'Check cable connections: unplug and firmly reconnect HDMI/DisplayPort cable',
      'Try a different cable or port — cables often fail before monitors',
      'Change display refresh rate: Settings → Display → Advanced display → Refresh rate (try 60Hz)',
      'Update or roll back display driver: Device Manager → Display adapters → Update driver',
      'Boot into Safe Mode: if flickering stops in Safe Mode, the cause is a driver or app',
      'Check if Task Manager flickers: if yes → driver issue; if no → software/app issue',
      'Disable hardware acceleration in Chrome/Firefox: Settings → System → Use hardware acceleration when available',
      'Check for EMI: keep power cables away from display cables; try different outlet',
    ],
    tags: ['flickering', 'screen', 'display', 'monitor', 'flicker', 'driver', 'hdmi'],
    category: 'hardware',
    successRate: 78,
    usageCount: 145,
    addedBy: 'Priya Nair',
    createdAt: '2026-04-22',
  },
  {
    id: 's19',
    title: 'Software Installation Blocked by IT Policy',
    description: 'Understand and resolve software blocked by AppLocker, WDAC, or Group Policy.',
    steps: [
      'Note the exact error message: "This app has been blocked by your system administrator" vs. "Access is denied"',
      'Check if software is approved in IT catalog — request via IT service desk',
      'IT Admin: check AppLocker policy: Run → gpedit.msc → Computer Configuration → Application Control Policies',
      'Check Windows Defender Application Control (WDAC) policy logs in Event Viewer',
      'IT Admin: add application to AppLocker exception list if approved',
      'For MSI: IT admin can deploy via Group Policy Software Installation or SCCM/Intune',
      'Contact IT to use winget install if available in the network environment',
      'Never disable security policies to install unapproved software — escalate properly',
    ],
    tags: ['blocked', 'applocker', 'policy', 'software install', 'access denied', 'admin rights'],
    category: 'security',
    successRate: 71,
    usageCount: 167,
    addedBy: 'Sara Mendez',
    createdAt: '2026-04-25',
  },
  {
    id: 's20',
    title: 'BitLocker Recovery Key Required at Boot',
    description: 'Recover a BitLocker-encrypted drive when the recovery key is requested on startup.',
    steps: [
      'Note the Recovery Key ID shown on screen (first 8 characters)',
      'Find recovery key in Microsoft account: account.microsoft.com → Devices → View BitLocker keys',
      'IT Admin: find key in Azure AD / Intune: Endpoint Manager → Devices → find device → Recovery keys',
      'Find key in Active Directory (if domain-joined): ADUC → Computer object → BitLocker Recovery tab',
      'Enter the 48-digit recovery key when prompted on boot',
      'After logging in: suspend and resume BitLocker to prevent future prompts',
      'Check if TPM cleared: Settings → BitLocker → Suspend protection → then Resume',
      'If key not found: contact IT immediately — data recovery options are very limited without the key',
    ],
    tags: ['bitlocker', 'recovery key', 'boot', 'encryption', 'tpm', 'locked drive'],
    category: 'security',
    successRate: 77,
    usageCount: 89,
    addedBy: 'Priya Nair',
    createdAt: '2026-04-28',
  },
  {
    id: 's21',
    title: 'Shared Mailbox / Distribution Group Access Denied',
    description: 'Fix "You do not have permission" errors when accessing shared mailboxes in Outlook.',
    steps: [
      'IT Admin: confirm user is member of the shared mailbox: Exchange Admin Center → Recipients → Shared → open mailbox → delegation',
      'Add Full Access permission: Exchange Admin Center → shared mailbox → Manage mailbox delegation → Add',
      'Allow up to 60 minutes for Active Directory permissions to propagate',
      'User: close and restart Outlook, then auto-mapping should add the mailbox',
      'If auto-mapping fails: manually add in Outlook → File → Account Settings → More Settings → Advanced → Add',
      'For mobile (Outlook app): add as additional account using shared mailbox email + user\'s own credentials',
      'Check if mailbox has legal hold or inactive status that restricts access',
      'For Send As permission: go to Exchange Admin Center → Shared → Send on behalf delegation',
    ],
    tags: ['shared mailbox', 'exchange', 'outlook', 'access denied', 'email permission', 'delegation'],
    category: 'software',
    successRate: 84,
    usageCount: 192,
    addedBy: 'Alex Reeves',
    createdAt: '2026-05-01',
  },
  {
    id: 's22',
    title: 'IP Address Conflict',
    description: 'Resolve "Windows has detected an IP address conflict" network errors.',
    steps: [
      'Open CMD as admin → run: ipconfig /release then ipconfig /renew',
      'If static IP: check for duplicate assignment with another device on network',
      'Run: arp -a to see current IP-to-MAC mappings and identify conflicting device',
      'Network Admin: check DHCP server for duplicate static reservations',
      'Change to DHCP: Network settings → adapter → Properties → IPv4 → Obtain IP automatically',
      'For static IP conflict: coordinate with network admin to assign unique static IP range',
      'Flush DNS: ipconfig /flushdns to clear stale cache',
      'Check if rogue DHCP server is operating on the network (security risk)',
    ],
    tags: ['ip conflict', 'ip address', 'dhcp', 'network', 'duplicate ip', 'arp'],
    category: 'network',
    successRate: 92,
    usageCount: 134,
    addedBy: 'Jake Torres',
    createdAt: '2026-05-03',
  },
  {
    id: 's23',
    title: 'DNS Not Resolving Internal Hosts',
    description: 'Fix issues where internal server names (not IPs) cannot be resolved within the network.',
    steps: [
      'Test DNS: nslookup servername → if it fails but IP works, it\'s a DNS issue',
      'Check DNS server setting: ipconfig /all → look at DNS Servers line',
      'Flush DNS cache: ipconfig /flushdns',
      'Try resolving with explicit DNS: nslookup servername 192.168.1.1 (internal DNS IP)',
      'Check if you\'re connected to correct network/VPN — remote users need VPN for internal DNS',
      'Test with external DNS: nslookup google.com 8.8.8.8 — if this works, internal DNS is the issue',
      'IT Admin: check DNS server health on Domain Controller: dnscmd /statistics',
      'Check for DNS split-brain configuration if accessing both internal and external same-name resources',
    ],
    tags: ['dns', 'internal dns', 'hostname', 'nslookup', 'name resolution', 'domain'],
    category: 'network',
    successRate: 80,
    usageCount: 112,
    addedBy: 'Omar Hassan',
    createdAt: '2026-05-05',
  },
  {
    id: 's24',
    title: 'Windows Won\'t Boot / Stuck on Loading Screen',
    description: 'Recover Windows that gets stuck on loading, spinning dots, or login screen.',
    steps: [
      'Force power off 3 times in a row — Windows will enter Automatic Repair mode',
      'In recovery: Troubleshoot → Advanced options → Startup Repair (let it run)',
      'If Startup Repair fails: Advanced options → Command Prompt → run: sfc /scannow',
      'Boot to safe mode: Advanced options → Startup Settings → press F4 (Safe Mode)',
      'From safe mode: uninstall recently installed updates or drivers that may have broken boot',
      'Check disk: CMD → chkdsk C: /f /r /x (marks bad sectors)',
      'Rebuild BCD: bootrec /fixmbr → bootrec /fixboot → bootrec /rebuildbcd',
      'Last resort: Reset this PC from Recovery → Keep my files option',
    ],
    tags: ['boot', 'not booting', 'stuck loading', 'startup repair', 'safe mode', 'bootrec'],
    category: 'hardware',
    successRate: 68,
    usageCount: 98,
    addedBy: 'Sara Mendez',
    createdAt: '2026-05-08',
  },
  {
    id: 's25',
    title: 'Monitor Shows "No Signal" / Black Screen',
    description: 'Fix external monitor showing No Signal or black screen after sleep/boot.',
    steps: [
      'Check cable connections: unplug and replug monitor cable at both ends',
      'Try a different cable (HDMI/DisplayPort cables fail without visible damage)',
      'Try a different input on the monitor (HDMI 1 vs HDMI 2 vs DP)',
      'Press Win+P to cycle display modes: PC screen only, Duplicate, Extend, Second screen only',
      'If second monitor: right-click desktop → Display settings → Detect',
      'Check if monitor power light is on — power button/standby issue vs. signal issue',
      'Try connecting to different port on GPU (first HDMI port may be for integrated graphics)',
      'Boot in Safe Mode: if monitor works in Safe Mode, issue is GPU driver — update or rollback',
    ],
    tags: ['no signal', 'monitor', 'black screen', 'display', 'hdmi', 'second monitor'],
    category: 'hardware',
    successRate: 76,
    usageCount: 187,
    addedBy: 'Alex Reeves',
    createdAt: '2026-05-10',
  },
  {
    id: 's26',
    title: 'Teams Meeting Audio / Video Not Working',
    description: 'Fix microphone, camera, or audio output issues during Microsoft Teams meetings.',
    steps: [
      'During call: check audio/video settings icon → confirm correct mic, speaker, and camera are selected',
      'Check Windows privacy: Settings → Privacy → Microphone → allow Teams',
      'Check Windows privacy: Settings → Privacy → Camera → allow Teams',
      'Update audio/video drivers (see Device Manager)',
      'Test with Teams test call: Profile picture → Settings → Devices → Make a test call',
      'Exit and reopen Teams — sometimes a fresh session fixes audio routing issues',
      'For "others can\'t hear me": right-click speaker icon → Sounds → Recording → set correct mic as Default',
      'Disable exclusive mode: Recording → mic Properties → Advanced → uncheck exclusive mode',
    ],
    tags: ['teams audio', 'teams mic', 'teams camera', 'meeting', 'microphone not working', 'mute'],
    category: 'software',
    successRate: 87,
    usageCount: 378,
    addedBy: 'Priya Nair',
    createdAt: '2026-05-12',
  },
  {
    id: 's27',
    title: 'Browser Running Slow / Crashing',
    description: 'Fix Google Chrome or Edge being slow, freezing, or crashing frequently.',
    steps: [
      'Close unused tabs — each tab uses memory; use "Tab Groups" to manage',
      'Clear cache and cookies: Ctrl+Shift+Delete → select all time → clear data',
      'Disable extensions: Settings → Extensions → disable all → re-enable one by one to find culprit',
      'Disable hardware acceleration: Settings → System → Use hardware acceleration when available → toggle off → relaunch',
      'Check memory usage: Shift+Esc (Chrome Task Manager) to identify heavy tabs/extensions',
      'Update browser: Settings → Help → About → check for updates',
      'Reset browser settings: Settings → Reset settings → Restore settings to their original defaults',
      'For malware: run Malwarebytes free scan — browser hijackers often cause this',
    ],
    tags: ['browser', 'chrome', 'edge', 'slow', 'crashing', 'extension', 'cache'],
    category: 'software',
    successRate: 85,
    usageCount: 256,
    addedBy: 'Omar Hassan',
    createdAt: '2026-05-14',
  },
  {
    id: 's28',
    title: 'SAP Fiori App Not Visible / Missing Tile',
    description: 'Fix missing SAP Fiori apps, tiles, or access issues in SAP S/4HANA launchpad.',
    steps: [
      'Hard refresh the Fiori Launchpad: Ctrl+Shift+R or clear browser cache',
      'Check business role assignment: SAP GUI → SU01 → check user\'s roles include the relevant business catalog',
      'IT Admin: SAP Fiori Config Cockpit → Verify app is assigned to the business role',
      'Check if app requires additional authorization objects: ST01 trace or SU53 for auth failures',
      'For Fiori 3.0: check if "Space" and "Page" configuration is correct in NWBC/FLP',
      'Try running the app directly via transaction code (SAP GUI) to verify backend authorization',
      'Check if the Fiori catalog was recently published: run /n/UI2/FLP_CONF_DEF in SAP GUI',
      'For OData errors: check SM59 destinations and ICM service bindings',
    ],
    tags: ['sap', 'fiori', 'missing tile', 'app access', 'authorization', 'business role', 'launchpad'],
    category: 'erp',
    successRate: 74,
    usageCount: 134,
    addedBy: 'Sara Mendez',
    createdAt: '2026-05-16',
  },
  {
    id: 's29',
    title: 'Password Expired / Reset Required',
    description: 'Handle password expiry, reset procedures, and account recovery.',
    steps: [
      'If on Windows login screen: Ctrl+Alt+Delete → Change password with old and new credentials',
      'If locked out from web: go to aka.ms/sspr (Microsoft Self-Service Password Reset)',
      'IT Admin: Active Directory reset → ADUC → right-click user → Reset Password',
      'For Entra ID: Azure Portal → Users → find user → Reset password → auto-generate',
      'Temporary password must be changed on first login — user must log in directly (not via RDP)',
      'Advise user to update password on all devices: phone, tablet, saved browser passwords',
      'Review password policy: minimum length, complexity, expiry days (typically 90 days)',
      'Enable SSPR (self-service password reset) for users: Azure AD → Password reset → Properties → All',
    ],
    tags: ['password', 'password expired', 'reset password', 'locked out', 'sspr', 'account'],
    category: 'identity',
    successRate: 97,
    usageCount: 521,
    addedBy: 'Alex Reeves',
    createdAt: '2026-05-18',
  },
  {
    id: 's30',
    title: 'Group Policy Not Applying / GPO Issues',
    description: 'Diagnose and fix Group Policy Objects not applying to computers or users.',
    steps: [
      'Force GPO refresh: CMD as admin → gpupdate /force',
      'Check which GPOs are applied: gpresult /r (command line) or gpresult /h gpreport.html (HTML report)',
      'Verify domain connectivity: nltest /dsgetdc:yourdomain.com',
      'Check GPO link status: GPMC → confirm GPO is linked and enabled to correct OU',
      'Check WMI filter on GPO: a failed WMI filter silently prevents GPO application',
      'Check GPO inheritance: look for "Block Inheritance" flag on the target OU',
      'Check Security Filtering: GPO → Scope → ensure "Authenticated Users" or target group has Read+Apply',
      'Event Viewer: Applications and Services Logs → Microsoft → Windows → Group Policy → Operational',
    ],
    tags: ['gpo', 'group policy', 'gpupdate', 'gpresult', 'domain', 'active directory', 'policy not applying'],
    category: 'identity',
    successRate: 78,
    usageCount: 145,
    addedBy: 'Priya Nair',
    createdAt: '2026-05-20',
  },
  {
    id: 's31',
    title: 'Microsoft Office (Word / Excel) Crashing',
    description: 'Fix Office apps that crash on launch, when opening specific files, or randomly.',
    steps: [
      'Open in Safe Mode: hold Ctrl while launching Word/Excel (tests for add-in conflict)',
      'If Safe Mode works: File → Options → Add-ins → Manage COM Add-ins → Go → disable all → re-enable one by one',
      'Repair Office: Control Panel → Programs → Microsoft Office → Change → Quick Repair',
      'If Quick Repair fails: Online Repair (requires internet, more thorough)',
      'Delete Normal.dotm template (Word): %appdata%\\Microsoft\\Templates → rename Normal.dotm to Normal.old',
      'Delete Excel personal macro file: %appdata%\\Microsoft\\Excel\\XLSTART → rename PERSONAL.xlsb',
      'Check for corrupted file: try File → Open → Browse → change file format filter → open different format',
      'Update Office: File → Account → Update Options → Update Now',
    ],
    tags: ['office', 'word', 'excel', 'crash', 'crashing', 'add-in', 'repair office'],
    category: 'software',
    successRate: 83,
    usageCount: 234,
    addedBy: 'Jake Torres',
    createdAt: '2026-05-22',
  },
  {
    id: 's32',
    title: 'MFA (Two-Factor Authentication) Not Working',
    description: 'Fix MFA issues: authenticator app not working, phone number outdated, or login blocked.',
    steps: [
      'Ensure phone time is synchronized — wrong time breaks TOTP codes: go to aka.ms/mfasetup',
      'Open Microsoft Authenticator app → tap account → "Refresh" to get fresh code',
      'Check phone notifications are enabled for Authenticator app',
      'If phone lost/changed: IT Admin can reset MFA: Azure AD → Users → find user → Authentication methods → Require re-register MFA',
      'Try using backup method: SMS code if configured',
      'Call IT helpdesk with identity verification to get emergency access',
      'For "Conditional Access blocked": check if device is compliant in Intune (Settings → Accounts → Access work or school)',
      'Re-register MFA: aka.ms/mfasetup → Add method → choose Authenticator or phone',
    ],
    tags: ['mfa', 'two-factor', 'authenticator', 'microsoft authenticator', 'conditional access', 'sign-in blocked'],
    category: 'identity',
    successRate: 89,
    usageCount: 367,
    addedBy: 'Sara Mendez',
    createdAt: '2026-05-24',
  },
  {
    id: 's33',
    title: 'ERP System Login Error (Dynamics 365 / Oracle / SAP)',
    description: 'Troubleshoot ERP login failures, authentication errors, and access denied.',
    steps: [
      'Confirm username format: some ERPs require domain\\username, some require user@domain.com, and some a SAP-specific username',
      'Check if password has expired in ERP system (separate from Windows password)',
      'Clear browser cache and try Incognito/InPrivate mode (browser-cached credentials often cause issues)',
      'Check SSO integration: if using Azure AD SSO, verify the user\'s Azure account is properly synced',
      'IT Admin: check user provisioning status in ERP — account may be inactive or deprovisioned',
      'Verify user has the correct security roles/licenses assigned in the ERP',
      'Check ERP system status: contact vendor or check status page for planned maintenance',
      'For SAP: check SM50 (work process overview) and SM21 (system log) for error details',
    ],
    tags: ['erp', 'dynamics', 'oracle', 'sap', 'login error', 'access denied', 'system'],
    category: 'erp',
    successRate: 76,
    usageCount: 187,
    addedBy: 'Alex Reeves',
    createdAt: '2026-05-26',
  },
  {
    id: 's34',
    title: 'Windows Activation / License Issue',
    description: 'Fix Windows activation errors and "Your Windows license will expire soon" messages.',
    steps: [
      'Check activation status: Settings → Update & Security → Activation',
      'Run: slmgr /ato to attempt online activation',
      'Check network connectivity to Microsoft activation servers (requires internet)',
      'For KMS activation (domain-joined): slmgr /skms kms-server.domain.com then slmgr /ato',
      'Error 0xC004C003: license key has been used too many times — contact Microsoft or IT',
      'Error 0xC004F074: KMS server not found — contact IT to configure correct KMS host',
      'Re-enter product key: Settings → Update & Security → Activation → Change product key',
      'For volume licensed (enterprise): IT admin can reactivate via KMS or MAK',
    ],
    tags: ['windows activation', 'license', 'not activated', 'kms', 'product key', 'activation error'],
    category: 'software',
    successRate: 82,
    usageCount: 134,
    addedBy: 'Omar Hassan',
    createdAt: '2026-05-28',
  },
  {
    id: 's35',
    title: 'Laptop Battery Draining Fast',
    description: 'Diagnose excessive battery drain and improve battery life.',
    steps: [
      'Check Battery report: CMD → powercfg /batteryreport → open C:\\Windows\\System32\\battery-report.html',
      'Change power plan: Settings → Power & sleep → Additional power settings → choose Balanced or Power saver',
      'Check battery health: report shows "Design Capacity" vs "Full Charge Capacity" — if <80%, battery needs replacement',
      'Find power-hungry apps: Settings → Battery → see which apps consume most',
      'Reduce screen brightness: Settings → Display → Brightness (biggest single drain)',
      'Disable Bluetooth and WiFi when not in use',
      'Adjust sleep settings: Settings → Power & sleep → set screen off after 5 min, sleep after 10 min',
      'If battery health <60% of design capacity: submit hardware replacement request to IT',
    ],
    tags: ['battery', 'laptop', 'battery drain', 'power', 'battery life', 'powercfg'],
    category: 'hardware',
    successRate: 73,
    usageCount: 145,
    addedBy: 'Jake Torres',
    createdAt: '2026-05-30',
  },
  {
    id: 's36',
    title: 'Outlook Email Rules Not Working',
    description: 'Fix Outlook rules that stop working, skip emails, or don\'t run automatically.',
    steps: [
      'Check rule order: rules run top-to-bottom, earlier rules may "stop processing" further rules',
      'Open Rules: Home → Rules → Manage Rules & Alerts — check for "Stop processing more rules" checkbox',
      'Check if rule is enabled: verify checkbox is checked in Rules and Alerts dialog',
      'Rules only work when Outlook is open unless using Server-side rules — prefer "Move to folder" type (server-side)',
      'If using Cached Exchange Mode: sync issues may delay rule execution — File → Account Settings → Exchange server settings → reduce offline days',
      'Delete and recreate the problematic rule from scratch',
      'Check mailbox size: if mailbox is full, rules can fail silently',
      'For shared mailboxes: rules must be set up by someone with Full Access permission',
    ],
    tags: ['outlook', 'rules', 'email rules', 'inbox rules', 'not working', 'exchange'],
    category: 'software',
    successRate: 80,
    usageCount: 167,
    addedBy: 'Priya Nair',
    createdAt: '2026-06-01',
  },
  {
    id: 's37',
    title: 'Printer Printing Incorrect Colors / Blank Pages',
    description: 'Fix color printing issues, faded prints, or printer outputting blank pages.',
    steps: [
      'Run printer self-test: most printers have a self-test mode (hold test button while powering on) — confirms ink/hardware issue vs. software',
      'Print test page from Windows: Devices → Printers → right-click printer → Printer properties → Print Test Page',
      'Check ink/toner levels: printer display or manufacturer software',
      'Clean printhead: printer settings → Maintenance → Clean printhead (run 2-3 times if needed)',
      'For blank pages: check printer settings — if set to print in color but no color ink, color prints blank',
      'Re-seat ink cartridges: remove and firmly reinsert all cartridges',
      'For laser printers: "Drum Low" warning causes faded prints — check drum unit replacement',
      'Update or reinstall printer driver from manufacturer website',
    ],
    tags: ['printer', 'color printing', 'blank pages', 'faded', 'ink', 'toner', 'printhead'],
    category: 'hardware',
    successRate: 77,
    usageCount: 112,
    addedBy: 'Alex Reeves',
    createdAt: '2026-06-03',
  },
  {
    id: 's38',
    title: 'Azure / Microsoft 365 Single Sign-On (SSO) Not Working',
    description: 'Fix SSO failures when accessing Microsoft 365 or Azure-integrated apps.',
    steps: [
      'Clear browser cookies specifically for login.microsoft.com and login.microsoftonline.com',
      'Try Incognito/Private mode — determines if it\'s a cookie/extension issue',
      'Check if device is Azure AD joined or registered: Settings → Accounts → Access work or school',
      'For "AADSTS" error codes: note the full code (e.g., AADSTS50126 = invalid credentials, AADSTS50140 = token error)',
      'IT Admin: check Conditional Access policies — a new policy may block the user\'s device/location',
      'Verify the user\'s UPN matches their email address in Azure AD (common mismatch issue)',
      'Check application enterprise app configuration: Azure Portal → Enterprise Applications → check sign-in logs',
      'For browser SSO: ensure browser extension "Microsoft Single Sign On" is installed for Chrome/Firefox',
    ],
    tags: ['sso', 'single sign on', 'azure ad', 'microsoft 365', 'entra', 'aadsts', 'login failed'],
    category: 'identity',
    successRate: 81,
    usageCount: 234,
    addedBy: 'Sara Mendez',
    createdAt: '2026-06-05',
  },
  {
    id: 's39',
    title: 'Network Printer Not Accessible After IP Change',
    description: 'Reconnect to a network printer whose IP address has changed.',
    steps: [
      'Find new printer IP: print a configuration page from the printer (usually hold button on printer)',
      'Check printer IP via DHCP reservations: access router/DHCP server → look for printer MAC address',
      'Update port in Windows: Devices → Printers → right-click printer → Printer properties → Ports tab → Configure Port → enter new IP',
      'Alternatively: Remove and re-add the printer with new IP/hostname',
      'Ask network admin to set a DHCP reservation for the printer\'s MAC address (fixes recurring issue)',
      'Use printer hostname instead of IP: if DNS is configured, hostname never changes even if IP does',
      'For networked MFPs: access the printer\'s web admin interface to set a static IP',
    ],
    tags: ['network printer', 'printer ip', 'printer not found', 'ip changed', 'port'],
    category: 'network',
    successRate: 91,
    usageCount: 145,
    addedBy: 'Jake Torres',
    createdAt: '2026-06-08',
  },
  {
    id: 's40',
    title: 'Slow File Transfer Over Network (SMB/Network Share)',
    description: 'Diagnose and fix slow file copy speeds over LAN or mapped network drives.',
    steps: [
      'Test local copy speed first (same PC) to establish baseline',
      'Test with a large single file — many small files are always slower than one large file',
      'Check cable: on switch, look for the port LEDs — 1Gbps link shows different indicator than 100Mbps',
      'Run: Get-NetAdapter in PowerShell → check LinkSpeed (should be 1 Gbps or higher)',
      'Disable SMB bandwidth throttling: Set-SmbBandwidthLimit (if set) → Remove-SmbBandwidthLimit',
      'Enable SMB Multichannel if multiple NICs: Set-SmbClientConfiguration -EnableMultiChannel $true',
      'Check for antivirus real-time scanning on both client and server — add network share to exclusions',
      'On server: check disk performance with CrystalDiskMark to rule out storage bottleneck',
    ],
    tags: ['slow file transfer', 'smb', 'network share', 'slow copy', 'file server', 'bandwidth'],
    category: 'network',
    successRate: 72,
    usageCount: 98,
    addedBy: 'Omar Hassan',
    createdAt: '2026-06-10',
  },
]

export const mockTickets: Ticket[] = [
  {
    id: 't1',
    title: 'WiFi dropping every 30 minutes',
    description: 'My connection keeps dropping exactly every 30 min. Reconnects after 2-3 min.',
    priority: 'high',
    status: 'in_progress',
    category: 'network',
    userId: 'u3',
    userName: 'Jake Torres',
    assignedTo: 'Alex Reeves',
    createdAt: '2026-05-29T08:00:00Z',
    updatedAt: '2026-05-29T10:30:00Z',
    solutionsTried: ['s2'],
  },
  {
    id: 't2',
    title: 'Outlook keeps crashing on startup',
    description: 'Office 365 Outlook crashes immediately after the loading screen.',
    priority: 'critical',
    status: 'open',
    category: 'software',
    userId: 'u5',
    userName: 'Omar Hassan',
    createdAt: '2026-05-30T07:15:00Z',
    updatedAt: '2026-05-30T07:15:00Z',
    solutionsTried: [],
  },
  {
    id: 't3',
    title: 'Printer showing as offline in Finance dept',
    description: 'HP LaserJet in Finance not printing. Showing offline for 3 users.',
    priority: 'medium',
    status: 'open',
    category: 'hardware',
    userId: 'u1',
    userName: 'Alex Reeves',
    createdAt: '2026-05-30T09:00:00Z',
    updatedAt: '2026-05-30T09:00:00Z',
    solutionsTried: ['s3'],
  },
  {
    id: 't4',
    title: 'VPN not connecting for remote work',
    description: 'Error 789: L2TP connection attempt failed.',
    priority: 'high',
    status: 'resolved',
    category: 'network',
    userId: 'u5',
    userName: 'Omar Hassan',
    assignedTo: 'Sara Mendez',
    createdAt: '2026-05-28T14:00:00Z',
    updatedAt: '2026-05-29T11:00:00Z',
    solutionsTried: ['s6'],
  },
  {
    id: 't5',
    title: 'PC extremely slow after Windows update',
    description: 'After KB5034441 update, boot takes 8+ minutes and apps lag badly.',
    priority: 'high',
    status: 'in_progress',
    category: 'hardware',
    userId: 'u3',
    userName: 'Jake Torres',
    assignedTo: 'Priya Nair',
    createdAt: '2026-05-29T15:00:00Z',
    updatedAt: '2026-05-30T08:00:00Z',
    solutionsTried: ['s1'],
  },
  {
    id: 't6',
    title: 'Microsoft 365 MFA not working',
    description: "Getting 'your sign-in was blocked' for the entire sales team.",
    priority: 'critical',
    status: 'in_progress',
    category: 'software',
    userId: 'u4',
    userName: 'Priya Nair',
    assignedTo: 'Sara Mendez',
    createdAt: '2026-05-30T06:30:00Z',
    updatedAt: '2026-05-30T09:45:00Z',
    solutionsTried: ['s7'],
  },
]

export const mockNodes: SystemNode[] = [
  { id: 'n1', name: 'CORE-DC-01', type: 'server', status: 'healthy', cpu: 34, memory: 62, disk: 41, uptime: '187d', alerts: 0, x: 50, y: 50 },
  { id: 'n2', name: 'CORE-DC-02', type: 'server', status: 'warning', cpu: 78, memory: 85, disk: 55, uptime: '187d', alerts: 2, x: 75, y: 30 },
  { id: 'n3', name: 'FILE-SRV-01', type: 'storage', status: 'healthy', cpu: 22, memory: 44, disk: 88, uptime: '90d', alerts: 1, x: 25, y: 30 },
  { id: 'n4', name: 'NET-SW-CORE', type: 'network', status: 'healthy', cpu: 12, memory: 31, disk: 10, uptime: '365d', alerts: 0, x: 50, y: 20 },
  { id: 'n5', name: 'AZURE-VM-01', type: 'cloud', status: 'healthy', cpu: 45, memory: 58, disk: 62, uptime: '45d', alerts: 0, x: 80, y: 60 },
  { id: 'n6', name: 'APP-SRV-WEB', type: 'server', status: 'critical', cpu: 96, memory: 94, disk: 72, uptime: '23d', alerts: 5, x: 20, y: 65 },
  { id: 'n7', name: 'WS-FINANCE-01', type: 'workstation', status: 'warning', cpu: 55, memory: 71, disk: 91, uptime: '12d', alerts: 3, x: 60, y: 75 },
  { id: 'n8', name: 'BACKUP-NAS-01', type: 'storage', status: 'offline', cpu: 0, memory: 0, disk: 0, uptime: '0d', alerts: 1, x: 35, y: 75 },
]

export const mockAlerts: Alert[] = [
  { id: 'a1', nodeId: 'n6', nodeName: 'APP-SRV-WEB', message: 'CPU usage at 96% for 15+ minutes', severity: 'critical', timestamp: '2026-05-30T09:50:00Z', acknowledged: false },
  { id: 'a2', nodeId: 'n2', nodeName: 'CORE-DC-02', message: 'Memory usage exceeded 85%', severity: 'warning', timestamp: '2026-05-30T09:30:00Z', acknowledged: false },
  { id: 'a3', nodeId: 'n7', nodeName: 'WS-FINANCE-01', message: 'Disk usage at 91% — low space', severity: 'warning', timestamp: '2026-05-30T08:15:00Z', acknowledged: false },
  { id: 'a4', nodeId: 'n8', nodeName: 'BACKUP-NAS-01', message: 'Node unreachable — possible hardware failure', severity: 'critical', timestamp: '2026-05-30T07:00:00Z', acknowledged: true },
  { id: 'a5', nodeId: 'n3', nodeName: 'FILE-SRV-01', message: 'Disk usage approaching threshold (88%)', severity: 'warning', timestamp: '2026-05-30T06:45:00Z', acknowledged: true },
]
