import TopBar from '@/components/layout/TopBar'
import DocSection from '@/components/docs/DocSection'

const HARDWARE_DOCS = [
  {
    id: 'windows-network-diagnostics',
    title: 'Windows Network Diagnostics',
    icon: '🌐',
    color: 'cyan',
    sections: [
      {
        heading: 'Overview',
        content:
          'Windows includes a comprehensive suite of built-in network diagnostic tools accessible from Command Prompt or PowerShell. These tools cover IP configuration inspection, connectivity testing, route tracing, DNS resolution, port and connection monitoring, and stack resets. Run CMD or PowerShell as Administrator for full functionality. Most commands produce verbose output — pipe to a text file for documentation using > output.txt.',
      },
      {
        heading: 'Core Diagnostic Commands',
        items: [
          { label: 'Full IP Configuration (all adapters)', path: 'ipconfig /all' },
          { label: 'Release DHCP lease', path: 'ipconfig /release' },
          { label: 'Renew DHCP lease', path: 'ipconfig /renew' },
          { label: 'Flush DNS resolver cache', path: 'ipconfig /flushdns' },
          { label: 'Display DNS resolver cache', path: 'ipconfig /displaydns' },
          { label: 'Basic connectivity ping (4 packets)', path: 'ping 8.8.8.8' },
          { label: 'Continuous ping (press Ctrl+C to stop)', path: 'ping -t 8.8.8.8' },
          { label: 'Ping with large packet (test fragmentation)', path: 'ping -l 1472 -f 8.8.8.8' },
          { label: 'Trace route to destination', path: 'tracert 8.8.8.8' },
          { label: 'Tracert without DNS resolution (faster)', path: 'tracert -d 8.8.8.8' },
          { label: 'PathPing (combined ping + tracert with statistics)', path: 'pathping 8.8.8.8' },
          { label: 'DNS lookup for a hostname', path: 'nslookup google.com' },
          { label: 'Reverse DNS lookup for an IP', path: 'nslookup 8.8.8.8' },
          { label: 'Query specific DNS server', path: 'nslookup google.com 1.1.1.1' },
          { label: 'Show all active TCP/UDP connections', path: 'netstat -an' },
          { label: 'Show connections with process IDs', path: 'netstat -ano' },
          { label: 'Show routing table', path: 'route print' },
          { label: 'Show ARP cache (IP to MAC mapping)', path: 'arp -a' },
          { label: 'Test TCP port connectivity (PowerShell)', path: 'Test-NetConnection -ComputerName server.domain.com -Port 443' },
          { label: 'Test multiple ports quickly (PowerShell)', path: '1..1024 | % { $t = Test-NetConnection -ComputerName 192.168.1.1 -Port $_ -WarningAction SilentlyContinue; if($t.TcpTestSucceeded) { Write-Host "Port $_ OPEN" } }' },
        ],
      },
      {
        heading: 'TCP/IP and Winsock Reset Procedures',
        steps: [
          'Open Command Prompt as Administrator (Right-click Start → Windows Terminal (Admin) or search "cmd" → Run as administrator)',
          'Reset TCP/IP stack: netsh int ip reset C:\\tcp_reset.log — resets IPv4 settings to defaults, writes log to C:\\tcp_reset.log',
          'Reset IPv6 stack: netsh int ipv6 reset',
          'Reset Winsock catalog: netsh winsock reset — fixes corrupted LSP (Layered Service Provider) issues',
          'Reset firewall policies: netsh advfirewall reset',
          'Restart the computer for all resets to take effect — do not skip this step',
          'After reboot, verify IP config: ipconfig /all — confirm adapter shows correct IP, gateway, and DNS',
          'If still no connectivity: ipconfig /release then ipconfig /renew to force fresh DHCP lease',
          'Test gateway: ping <default gateway IP from ipconfig /all> — if this fails, issue is between PC and router',
          'Test DNS: nslookup google.com — if IP ping works but DNS fails, flush DNS: ipconfig /flushdns then retry',
        ],
      },
      {
        heading: 'Network Adapter Reset',
        steps: [
          'PowerShell: Get-NetAdapter — list all network adapters with status',
          'PowerShell: Disable adapter: Disable-NetAdapter -Name "Ethernet" -Confirm:$false',
          'PowerShell: Enable adapter: Enable-NetAdapter -Name "Ethernet" -Confirm:$false',
          'Or via Device Manager: Win+X → Device Manager → Network adapters → Right-click adapter → Disable device → then Enable device',
          'Reset adapter statistics: netsh int ip reset or via GUI: Network adapters → right-click → Uninstall device → reboot (Windows reinstalls automatically)',
          'Set static IP (PowerShell): New-NetIPAddress -InterfaceAlias "Ethernet" -IPAddress 192.168.1.100 -PrefixLength 24 -DefaultGateway 192.168.1.1',
          'Set DNS servers (PowerShell): Set-DnsClientServerAddress -InterfaceAlias "Ethernet" -ServerAddresses ("8.8.8.8","8.8.4.4")',
          'Return to DHCP (PowerShell): Set-NetIPInterface -InterfaceAlias "Ethernet" -Dhcp Enabled then ipconfig /renew',
        ],
      },
      {
        heading: 'Proxy Settings and Hosts File',
        steps: [
          'View current proxy settings: netsh winhttp show proxy',
          'Set system proxy: netsh winhttp set proxy proxy-server="http=proxy.company.com:8080" bypass-list="*.local;localhost"',
          'Reset/remove system proxy: netsh winhttp reset proxy',
          'Internet Explorer/Edge proxy (affects WinHTTP): Settings → Proxy → Manual proxy setup — note: this differs from WinHTTP',
          'Hosts file location: C:\\Windows\\System32\\drivers\\etc\\hosts — open with Notepad as Administrator',
          'Add local override in hosts file: add line 192.168.1.50  intranet.company.com — maps hostname to specific IP before DNS',
          'Flush DNS after editing hosts file: ipconfig /flushdns',
          'Check if hosts file is overriding DNS: nslookup hostname — if returned IP differs from expected, check hosts file',
          'Malware detection: a corrupted hosts file redirecting google.com or windowsupdate.com to unknown IPs is a sign of malware — inspect and clean',
        ],
      },
      {
        heading: 'Common Error Codes and Fixes',
        steps: [
          'Error: "General failure" on ping — TCP/IP stack is corrupt. Run: netsh int ip reset and netsh winsock reset then reboot',
          'Error: "Request timed out" — packet sent but no reply. Check firewall on target, verify route: tracert <destination>',
          'Error: "Destination host unreachable" — no route to host. Check routing table: route print, verify gateway IP',
          'Error: "Unknown host" on nslookup — DNS server unreachable or no record. Check DNS server IP in ipconfig /all, try nslookup with 8.8.8.8',
          'Error 0x8007274D (WSA_E_CONNREFUSED) — connection actively refused by target on that port. Verify service is running on target',
          'Error: Limited connectivity / 169.254.x.x IP — DHCP server not responding. Try ipconfig /release then /renew; check DHCP server and cable',
        ],
      },
    ],
  },
  {
    id: 'wifi-troubleshooting',
    title: 'WiFi Troubleshooting',
    icon: '📶',
    color: 'purple',
    sections: [
      {
        heading: 'Overview',
        content:
          'WiFi issues on Windows 10/11 range from driver problems and power management interference to channel congestion and protocol incompatibilities. The troubleshooting approach follows signal → driver → IP → DNS → authentication. Windows includes netsh wlan commands for in-depth wireless diagnostics. Always update WiFi adapter drivers before deep-diving into network settings, as outdated drivers cause the majority of intermittent wireless issues.',
      },
      {
        heading: 'WiFi Diagnostic Commands',
        items: [
          { label: 'List all available WiFi networks with signal', path: 'netsh wlan show networks mode=bssid' },
          { label: 'Show current WiFi connection details', path: 'netsh wlan show interfaces' },
          { label: 'List all saved WiFi profiles', path: 'netsh wlan show profiles' },
          { label: 'Show saved password for a network', path: 'netsh wlan show profile name="NetworkName" key=clear' },
          { label: 'Export all WiFi profiles (backup)', path: 'netsh wlan export profile folder=C:\\WiFiBackup key=clear' },
          { label: 'Delete (forget) a WiFi network', path: 'netsh wlan delete profile name="NetworkName"' },
          { label: 'Disconnect from current WiFi', path: 'netsh wlan disconnect' },
          { label: 'Connect to a saved WiFi profile', path: 'netsh wlan connect name="NetworkName"' },
          { label: 'Show WiFi driver capabilities and supported modes', path: 'netsh wlan show drivers' },
          { label: 'Generate WiFi diagnostic report (HTML)', path: 'netsh wlan show wlanreport' },
          { label: 'Check WiFi adapter power management (PowerShell)', path: 'Get-NetAdapterPowerManagement -Name "Wi-Fi" | Select-Object AllowComputerToTurnOffDevice' },
          { label: 'Disable WiFi power management (PowerShell)', path: 'Set-NetAdapterPowerManagement -Name "Wi-Fi" -AllowComputerToTurnOffDevice Disabled' },
        ],
      },
      {
        heading: 'Signal Strength and Frequency Band Issues',
        steps: [
          'Run: netsh wlan show networks mode=bssid — note Signal column (percentage). Below 50% causes poor performance',
          'Move closer to the access point or eliminate obstructions (walls, metal cabinets, microwave ovens cause 2.4GHz interference)',
          'Check frequency band in use: netsh wlan show interfaces — look for Radio type (802.11ac/ax = 5GHz capable, 802.11n can be either)',
          'Force 5GHz band: Device Manager → Network adapters → WiFi adapter → Properties → Advanced tab → Preferred band → Set to 5GHz',
          'If 5GHz shows lower signal than 2.4GHz: the 5GHz signal does not penetrate walls as well — stay closer to AP for 5GHz',
          '2.4GHz channel congestion: use WiFi Analyzer app (Microsoft Store) to see channel utilization — switch AP channel to 1, 6, or 11 (non-overlapping)',
          '5GHz channel congestion: channels 36, 40, 44, 48 (UNII-1) are best — avoid DFS channels (52-144) which require radar detection delays',
          'If neighboring networks are on same channel: access AP admin page (usually 192.168.1.1 or 192.168.0.1) → Wireless settings → Change channel',
        ],
      },
      {
        heading: 'Driver Update and Adapter Reset',
        steps: [
          'Identify adapter: Device Manager → Network adapters → note WiFi adapter name (e.g., Intel Wi-Fi 6 AX201)',
          'Update driver via Device Manager: right-click adapter → Update driver → Search automatically — often insufficient',
          'Download driver from manufacturer: Intel ARK (downloadcenter.intel.com), Realtek, Qualcomm — search adapter model → download latest',
          'Clean install: Device Manager → right-click adapter → Uninstall device → Check "Delete the driver software" → Reboot → Install downloaded driver',
          'Rollback if new driver causes issues: Device Manager → right-click adapter → Properties → Driver tab → Roll Back Driver',
          'Reset WiFi adapter: Device Manager → right-click adapter → Disable device → wait 10 seconds → Enable device',
          'Check adapter power settings: Device Manager → right-click adapter → Properties → Power Management → Uncheck "Allow the computer to turn off this device to save power"',
          'After driver update: run netsh wlan show drivers and confirm driver version and date are updated',
        ],
      },
      {
        heading: 'DHCP, Static IP, and WPA3 Compatibility',
        steps: [
          'Check if IP is DHCP or static: ipconfig /all — look for "DHCP Enabled: Yes/No" and "Autoconfiguration Enabled"',
          'If showing 169.254.x.x (APIPA): DHCP failed. Run: ipconfig /release then ipconfig /renew',
          'If DHCP still fails: try setting static IP temporarily — Control Panel → Network → Adapter Properties → IPv4 → Use following IP: 192.168.1.x / 255.255.255.0 / gateway: 192.168.1.1',
          'After testing, return to DHCP: same location → Obtain IP automatically',
          'WPA3 compatibility: older WiFi adapters (pre-2018) may not support WPA3. If AP is set to WPA3-only, device cannot connect',
          'Check WPA3 support: netsh wlan show drivers — look for "Authentication and cipher supported" — WPA3-Personal should appear',
          'Fix: on AP, set security to WPA2/WPA3 mixed mode (transition mode) — allows both old and new devices',
          'Wireless driver security settings: Device Manager → adapter → Properties → Advanced → look for 802.11w (Management Frame Protection) — set to Optional if WPA3 connection fails',
        ],
      },
      {
        heading: 'Common WiFi Error Codes',
        steps: [
          'Error "Windows cannot connect to [network]": forget and re-add the network, update driver, or check passphrase',
          'Error "No Internet, secured": IP obtained but default gateway or DNS unreachable. Ping gateway IP — if it fails, AP issue; if it works, DNS issue',
          'Error "Can\'t connect to this network": corrupted profile. Run: netsh wlan delete profile name="NetworkName" then reconnect from scratch',
          'Frequent disconnections: disable WiFi adapter power management, update driver, check for 2.4GHz interference from Bluetooth (share spectrum)',
          'Bluetooth interference: 2.4GHz WiFi and Bluetooth share spectrum. Try 5GHz WiFi or Device Manager → Bluetooth adapter → Properties → Advanced → Disable Bluetooth band',
          'Error "Authentication failed": wrong password, or security mismatch (AP uses TKIP, device expects AES). Check AP settings, use AES/CCMP only',
        ],
      },
    ],
  },
  {
    id: 'ethernet-lan-issues',
    title: 'Ethernet & LAN Issues',
    icon: '🔌',
    color: 'green',
    sections: [
      {
        heading: 'Overview',
        content:
          'Ethernet connectivity issues span physical layer (cable, port, NIC), data link layer (duplex, VLAN, 802.1x), and network layer (IP, routing) problems. Physical problems account for roughly 60% of Ethernet issues — always start with cable and port verification before investigating software configuration. Windows Event Viewer and Device Manager provide key diagnostic information for NIC-level issues.',
      },
      {
        heading: 'Ethernet Diagnostic Commands',
        items: [
          { label: 'Check Ethernet adapter status (PowerShell)', path: 'Get-NetAdapter -Name "Ethernet" | Select-Object Status, LinkSpeed, MediaType, FullDuplex' },
          { label: 'Check all adapter link speeds and duplex', path: 'Get-NetAdapter | Select-Object Name, Status, LinkSpeed, FullDuplex' },
          { label: 'View Ethernet adapter statistics', path: 'Get-NetAdapterStatistics -Name "Ethernet"' },
          { label: 'Check for duplex mismatch errors (PowerShell)', path: 'Get-NetAdapterStatistics | Select-Object Name, ReceivedPackets, ReceivedErrors, OutboundErrors' },
          { label: 'Show active Ethernet connections', path: 'netstat -ano | findstr ESTABLISHED' },
          { label: 'Show TCP connection states', path: 'netstat -s -p tcp' },
          { label: 'Check ARP cache for gateway MAC', path: 'arp -a' },
          { label: 'Test link-local connectivity (169.254.x.x range)', path: 'ping 169.254.0.1' },
          { label: 'Show all IP interfaces (PowerShell)', path: 'Get-NetIPInterface | Select-Object InterfaceAlias, AddressFamily, ConnectionState, Dhcp' },
          { label: 'Force duplex and speed settings (PowerShell)', path: 'Set-NetAdapterAdvancedProperty -Name "Ethernet" -RegistryKeyword "SpeedDuplex" -RegistryValue 6' },
          { label: 'Enable/disable jumbo frames (PowerShell)', path: 'Set-NetAdapterAdvancedProperty -Name "Ethernet" -RegistryKeyword "JumboPacket" -RegistryValue 9014' },
          { label: 'Enable Wake-on-LAN (PowerShell)', path: 'Set-NetAdapterPowerManagement -Name "Ethernet" -WakeOnMagicPacket Enabled' },
        ],
      },
      {
        heading: 'Cable and Physical Layer Testing',
        steps: [
          'Check link light on NIC and switch port — solid green or amber indicates physical link; no light means no physical connection',
          'Try a known-good cable — Cat5e minimum for gigabit, Cat6 recommended. Check for visible damage, sharp bends, or crimped connectors',
          'Test cable with a cable tester — checks for open wires, shorts, and miswired pairs (crossed pairs cause 100Mb but fail gigabit)',
          'Try a different switch port — ports can fail. Connect to another port on same switch to isolate',
          'Try a different device on same cable/port to isolate whether issue is with PC NIC or switch port',
          'Check cable length — Ethernet is rated to 100 meters maximum. Exceeding this causes intermittent errors, especially at gigabit speeds',
          'Inspect RJ45 connector — pins should be fully seated and in correct T568B order (orange-white, orange, green-white, blue, blue-white, green, brown-white, brown)',
          'Check for crimped or damaged patch panel jacks in server rooms — wiggle the cable at both ends while pinging to identify intermittent physical connections',
        ],
      },
      {
        heading: 'Duplex Mismatch and Speed Configuration',
        steps: [
          'Duplex mismatch symptom: connection works but extremely slow, high error rate in Get-NetAdapterStatistics. One end is half-duplex, other is full-duplex',
          'Check current setting: Device Manager → Network adapters → right-click NIC → Properties → Advanced → Speed & Duplex',
          'Both ends should be "Auto Negotiation" (recommended) OR both manually set to the same speed/duplex (e.g., both 1.0 Gbps Full Duplex)',
          'Fix via Device Manager: Advanced → Speed & Duplex → set to "1.0 Gbps Full Duplex" — match on switch port too',
          'Fix via PowerShell: Set-NetAdapterAdvancedProperty -Name "Ethernet" -RegistryKeyword "SpeedDuplex" -RegistryValue 6 (value 6 = 1Gbps Full Duplex)',
          'On managed switch: verify port speed and duplex via switch CLI or web interface — set to auto on both sides',
          'After changing: monitor adapter statistics: Get-NetAdapterStatistics -Name "Ethernet" — errors should drop to near zero',
          'SpeedDuplex registry values: 0=Auto, 1=10Mb Half, 2=10Mb Full, 3=100Mb Half, 4=100Mb Full, 6=1Gbps Full',
        ],
      },
      {
        heading: 'VLAN, 802.1x, and Link-Local Address Issues',
        steps: [
          'Link-local address (169.254.x.x): means DHCP failed. Check switch port VLAN — if PC is on wrong VLAN, DHCP server may be unreachable',
          'VLAN check: on managed switch, verify port PVID/access VLAN matches the expected network segment',
          'IEEE 802.1x authentication failure: PC cannot authenticate to switch port using NaC (Network Access Control). Check: Event Viewer → System → look for "Failed to authenticate" or "EAPOL" events',
          'Disable 802.1x temporarily to test: Control Panel → Network and Sharing → Adapter Properties → Authentication tab → Disable IEEE 802.1X authentication',
          'Re-enable 802.1x properly: requires correct certificate or credentials. Contact network admin for NAC configuration',
          'Wake-on-LAN not working: verify WoL enabled in BIOS (Power Management section) AND in Windows: Device Manager → NIC → Properties → Power Management → Allow magic packet to wake computer',
          'Jumbo frames: for iSCSI or NFS performance, set MTU to 9000. Both ends must match — NIC, switch port, and storage controller. Test: ping with large packet: ping -l 8972 -f <storage IP>',
          'If jumbo frame ping fails: one device in path does not support jumbo frames. Switch back to standard 1500 MTU',
        ],
      },
      {
        heading: 'Common Ethernet Error Patterns',
        steps: [
          'Packet loss on internal network: check cable, try different switch port, run Get-NetAdapterStatistics and watch for increasing error counts',
          'Gigabit NIC only negotiating 100Mbps: cable may be faulty (need all 4 pairs for gigabit vs 2 pairs for 100Mb), or switch port is 100Mb-only',
          'IP conflict (two devices same IP): arp -a shows duplicate MAC for same IP, or Windows pops "IP address conflict" notification. Check DHCP reservations or static assignments',
          'IP conflict fix: change static IP or update DHCP scope to exclude conflicting range',
          'NIC not appearing in Device Manager: check PCI slot seating for desktop, try different slot. For laptop, check BIOS LAN enable setting',
          'Ethernet "Unidentified network" in Windows: IP obtained but gateway unreachable or gateway not set. Verify gateway in ipconfig /all and that gateway device is online',
        ],
      },
    ],
  },
  {
    id: 'hardware-diagnostics-windows',
    title: 'Hardware Diagnostics — Windows',
    icon: '🔧',
    color: 'amber',
    sections: [
      {
        heading: 'Overview',
        content:
          'Windows provides several built-in tools for hardware diagnostics, supplemented by free third-party utilities. Device Manager surfaces driver conflicts, unknown devices, and hardware errors. Event Viewer logs hardware-related critical and error events with detailed codes. Windows Memory Diagnostic tests RAM for errors. For storage health, CrystalDiskInfo reads SMART data. CPU-Z provides detailed CPU/RAM/motherboard specs. Temperature monitoring helps identify thermal throttling before hardware damage occurs.',
      },
      {
        heading: 'Built-in Diagnostic Tools',
        items: [
          { label: 'Open Device Manager', path: 'Win+X → Device Manager  OR  devmgmt.msc' },
          { label: 'Open Event Viewer', path: 'Win+X → Event Viewer  OR  eventvwr.msc' },
          { label: 'Open System Information (detailed specs)', path: 'msinfo32' },
          { label: 'Open DirectX Diagnostic Tool', path: 'dxdiag' },
          { label: 'Windows Memory Diagnostic (RAM test on reboot)', path: 'mdsched.exe' },
          { label: 'Reliability Monitor (hardware/software error history)', path: 'perfmon /rel' },
          { label: 'Performance Monitor (real-time counters)', path: 'perfmon' },
          { label: 'Resource Monitor (CPU, Memory, Disk, Network live)', path: 'resmon' },
          { label: 'Check disk health via SMART (PowerShell)', path: 'Get-PhysicalDisk | Select-Object FriendlyName, HealthStatus, OperationalStatus, Size' },
          { label: 'List all physical drives', path: 'wmic diskdrive get model, serialnumber, size, status' },
          { label: 'Get CPU information (PowerShell)', path: 'Get-WmiObject Win32_Processor | Select-Object Name, NumberOfCores, NumberOfLogicalProcessors, MaxClockSpeed' },
          { label: 'Get RAM information (PowerShell)', path: 'Get-WmiObject Win32_PhysicalMemory | Select-Object Manufacturer, Capacity, Speed, MemoryType' },
          { label: 'Get motherboard information (PowerShell)', path: 'Get-WmiObject Win32_BaseBoard | Select-Object Manufacturer, Product, SerialNumber' },
          { label: 'Check hardware errors in Event Log (PowerShell)', path: 'Get-EventLog -LogName System -EntryType Error -Newest 50 | Select-Object TimeGenerated, Source, EventID, Message' },
          { label: 'Check critical events last 24 hours (PowerShell)', path: 'Get-WinEvent -FilterHashtable @{LogName="System"; Level=1; StartTime=(Get-Date).AddDays(-1)} | Select-Object TimeCreated, Id, Message' },
        ],
      },
      {
        heading: 'Device Manager Troubleshooting',
        steps: [
          'Open Device Manager: Win+X → Device Manager or devmgmt.msc',
          'Look for yellow exclamation marks (!) — indicates driver problem or hardware conflict',
          'Red X on device — device is disabled. Right-click → Enable device',
          'Unknown devices (question mark): right-click → Properties → Details tab → Hardware IDs — copy the first ID (e.g., PCI\\VEN_8086&DEV_1234) and search on PCI IDs database (pci-ids.ucw.cz) or DriverIdentifier',
          'View hidden devices: View menu → Show hidden devices — reveals ghosted (previously connected) hardware and software drivers',
          'Driver details: right-click device → Properties → Driver tab → Driver Details — shows .sys file location',
          'Check for hardware errors: right-click device → Properties → Events tab — shows driver load events and errors with timestamps',
          'Scan for hardware changes: Action menu → Scan for hardware changes — useful after installing new hardware',
          'Export device list: Action → Print → Save as text file for documentation or troubleshooting tickets',
        ],
      },
      {
        heading: 'Event Viewer Critical Error Investigation',
        steps: [
          'Open Event Viewer: eventvwr.msc or Win+X → Event Viewer',
          'Navigate to: Windows Logs → System — filter by Level: Critical and Error',
          'Create custom view: right panel → Create Custom View → set time range (last 7 days), Level (Critical, Error), Logs (System, Application) → name the view',
          'Key hardware event IDs: 41 (Kernel-Power — unexpected shutdown/reboot), 1001 (BugCheck — BSOD stop code), 7 (disk errors from disk driver), 15 (hardware failure)',
          'Event ID 41: kernel power critical — caused by overheating, PSU failure, RAM error, or driver crash causing hard shutdown. Check temperatures and run Memory Diagnostic',
          'Event ID 7 (disk): The device, \\Device\\Harddisk0, has a bad block — imminent disk failure. Back up immediately and replace disk',
          'For BSOD crashes: Windows Logs → System → find Event ID 1001 (Windows Error Reporting) → the stop code tells root cause. Search Microsoft error database at docs.microsoft.com',
          'Export log for analysis: right-click Log → Save All Events As → .evtx file — share with vendor or advanced support',
        ],
      },
      {
        heading: 'RAM Testing with Windows Memory Diagnostic',
        steps: [
          'Open Windows Memory Diagnostic: mdsched.exe → Restart now and check for problems (saves work first)',
          'Or schedule for next reboot: mdsched.exe → Check for problems the next time I start my computer',
          'During test: press F1 to change test settings — Standard (default), Basic (quick), or Extended (thorough, takes hours for large RAM)',
          'Wait for test to complete — PC reboots, runs tests (shown as percentage complete), then boots Windows',
          'View results: Event Viewer → Windows Logs → System → search for source "MemoryDiagnostics-Results" → Event ID 1201 or 1101',
          'If errors found: indicates faulty RAM. Test each DIMM individually — remove all but one stick, run test, swap sticks to identify the bad module',
          'For thorough testing (overnight): third-party tool MemTest86 (free, bootable USB from memtest86.com) — more comprehensive than Windows tool',
          'Common RAM failure symptoms: BSOD with stop codes MEMORY_MANAGEMENT, IRQL_NOT_LESS_OR_EQUAL, UNEXPECTED_KERNEL_MODE_TRAP',
          'After replacing RAM: run Diagnostic again to confirm errors gone before returning to service',
        ],
      },
      {
        heading: 'Temperature Monitoring',
        steps: [
          'Windows does not include a built-in temperature monitor — use free tools: HWiNFO64 (hwinfo.com), Core Temp (alcpu.com/CoreTemp), or Open Hardware Monitor',
          'Safe temperature ranges: CPU idle 30-50°C, CPU load up to 80°C (Intel) or 90°C (AMD Ryzen). Above 95°C triggers thermal throttling',
          'GPU: idle 30-50°C, load up to 85°C typical. Above 90°C sustained indicates cooling problem',
          'NVMe SSD: normal 40-60°C under load. Above 70°C causes throttling. Check via HWiNFO64 or CrystalDiskInfo',
          'Thermal throttling detection: CPU-Z → Bench tab — compare score vs expected. If significantly lower, check temperatures under load',
          'If CPU/GPU overheating: clean dust from heatsinks and fans using compressed air. Check that all fans spin. Replace thermal paste if >3 years old (use MX-4 or Noctua NT-H1)',
          'Check laptop thermal performance: dxdiag → Display tab → Note feature levels — can indicate GPU throttling from thermal protection',
          'BIOS temperature readings: enter BIOS (F2/F10/Del on boot) → Hardware Monitor or PC Health Status — shows real-time CPU and motherboard temps',
        ],
      },
    ],
  },
  {
    id: 'pc-performance-troubleshooting',
    title: 'PC Performance Troubleshooting',
    icon: '⚡',
    color: 'cyan',
    sections: [
      {
        heading: 'Overview',
        content:
          'PC performance degradation on Windows 10/11 typically stems from high CPU utilization (background processes, malware, runaway services), memory pressure (insufficient RAM or memory leaks), disk I/O bottlenecks (HDD vs SSD, failing drive), or startup program overload. Use Task Manager as the first diagnostic tool, then drill down with Resource Monitor and Performance Monitor for detailed analysis. Addressing startup programs, services, and power plan settings provides the fastest performance improvements without hardware changes.',
      },
      {
        heading: 'Performance Diagnostic Commands',
        items: [
          { label: 'Open Task Manager (processes, performance, startup)', path: 'Ctrl+Shift+Esc  OR  taskmgr' },
          { label: 'Open Resource Monitor (detailed CPU/memory/disk/network)', path: 'resmon  OR  Task Manager → Performance tab → Open Resource Monitor' },
          { label: 'List processes by CPU usage (PowerShell)', path: 'Get-Process | Sort-Object CPU -Descending | Select-Object -First 20 Name, CPU, WorkingSet, Id' },
          { label: 'List processes by memory usage (PowerShell)', path: 'Get-Process | Sort-Object WorkingSet -Descending | Select-Object -First 20 Name, @{N="MB";E={[math]::Round($_.WorkingSet/1MB,1)}}, Id' },
          { label: 'Check disk I/O usage (PowerShell)', path: 'Get-Counter "\\PhysicalDisk(*)\\Disk Bytes/sec" -SampleInterval 2 -MaxSamples 10' },
          { label: 'Check disk queue length (should be <2)', path: 'Get-Counter "\\PhysicalDisk(*)\\Current Disk Queue Length" -SampleInterval 1 -MaxSamples 10' },
          { label: 'List startup programs (PowerShell)', path: 'Get-CimInstance Win32_StartupCommand | Select-Object Name, Command, Location, User' },
          { label: 'List startup impact in Task Manager', path: 'Task Manager → Startup apps tab → sort by Startup impact column' },
          { label: 'Check Windows services status', path: 'Get-Service | Where-Object {$_.Status -eq "Running"} | Sort-Object DisplayName | Select-Object DisplayName, Name' },
          { label: 'Check current power plan', path: 'powercfg /getactivescheme' },
          { label: 'List all power plans', path: 'powercfg /list' },
          { label: 'Set High Performance power plan', path: 'powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c' },
          { label: 'Generate detailed power report', path: 'powercfg /energy — generates energy-report.html in current directory' },
          { label: 'Generate sleep study report', path: 'powercfg /sleepstudy' },
        ],
      },
      {
        heading: 'High CPU Usage Investigation',
        steps: [
          'Open Task Manager: Ctrl+Shift+Esc → CPU column — click to sort by CPU descending',
          'Identify the top CPU consumer. Common culprits: antivirus scan (MsMpEng.exe), Windows Update (TiWorker.exe, wuauclt.exe), system indexing (SearchIndexer.exe)',
          'For MsMpEng.exe (Windows Defender) high CPU: often during scheduled scan. Check: Settings → Windows Security → Virus & threat protection → Scan options → ensure no full scan running. Add C:\\ProgramData\\Microsoft and temp folders to exclusions if appropriate',
          'For TiWorker.exe / WaasMedic.exe (Windows Update): wait for updates to complete, or pause updates: Settings → Windows Update → Pause updates for 1 week',
          'For SearchIndexer.exe: Settings → Search → Searching Windows → Excluded Folders — add data folders to exclusion, or disable indexing: Services → Windows Search → Startup type: Manual',
          'Unknown high-CPU process: right-click in Task Manager → Open file location — verify it is a legitimate Windows or app process. Suspicious locations (Temp, AppData\\Roaming) may indicate malware',
          'Check for malware: run Windows Defender offline scan or Malwarebytes Free — high CPU from unknown processes often indicates cryptominer',
          'Persistent CPU issues: use Process Monitor (Sysinternals, free from microsoft.com/sysinternals) to trace every file/registry/network call of suspicious process',
        ],
      },
      {
        heading: 'Memory Pressure and Disk I/O Bottleneck',
        steps: [
          'Check memory in Task Manager: Performance tab → Memory — watch In Use vs Available. Below 500MB available means memory pressure',
          'If memory usage >90%: check for memory leaks. Sort processes by Memory column — look for process growing over time',
          'Identify memory leaks: Resource Monitor → Memory tab → watch Commit column for a process growing without shrinking',
          'Quick fix for memory pressure: close unused browser tabs (each tab = 50-200MB), close unused applications',
          'Disk I/O bottleneck: Task Manager → Performance → Disk — if Disk utilization is at 100% consistently, this is the bottleneck',
          'Identify disk hog: Resource Monitor → Disk tab → processes sorted by Total disk activity',
          'Superfetch/SysMain causing disk activity: Services.msc → SysMain → if on HDD causing constant 100% disk: change Startup type to Disabled → Stop. Note: this helps on HDDs, leave enabled on SSDs',
          'Virtual memory (pagefile) on disk: if RAM is maxed, Windows uses pagefile causing heavy disk I/O. Fix: add more RAM or increase pagefile on fastest available disk',
          'Check if disk is HDD or SSD: Get-PhysicalDisk | Select-Object FriendlyName, MediaType — SSD performance is far better for OS operations',
        ],
      },
      {
        heading: 'Startup Optimization and Services',
        steps: [
          'Task Manager → Startup apps tab — disable high-impact items that are not needed at boot (Teams, OneDrive, Spotify, Discord auto-start)',
          'Or via Settings: Apps → Startup — toggle off unnecessary startup apps',
          'Startup folder locations: C:\\Users\\<user>\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup and C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Startup',
          'Service optimization: Win+R → services.msc — change these non-essential services to Manual (not Disabled, as apps may need them): Print Spooler (if no printer), Fax, Windows Search (if not using search), Remote Desktop Services (if not using RDP)',
          'Never disable: Windows Update, Windows Defender, DNS Client, DHCP Client, RPC services — disabling core services breaks Windows',
          'Power plan: Win+R → powercfg.cpl → choose High Performance or Balanced. Power Saver reduces CPU clock speed significantly',
          'Visual effects reduction: Win+R → sysdm.cpl → Advanced → Performance → Settings → Adjust for best performance (disables animations)',
          'After optimization: reboot and measure boot time. Task Manager → Startup apps → Last BIOS time (top right) shows time from power-on to desktop',
        ],
      },
      {
        heading: 'Common Performance Issues and Fixes',
        steps: [
          'Slow boot (>3 minutes on SSD): too many startup programs, or SSD health issue. Disable startup apps, check SSD SMART in CrystalDiskInfo',
          'Slow file operations: check antivirus real-time scanning is not excessive — add working folders to exclusions if security policy permits',
          'Lag after extended uptime: memory leak. Check uptime: Task Manager → Performance → CPU → Up time. If >7 days, schedule restart',
          'Sudden performance drop after Windows Update: rollback update if confirmed cause. Windows Update → View update history → Uninstall updates',
          'Thermal throttling causing slow performance: use HWiNFO64 to check if CPU frequency drops under load (thermal throttle) — clean PC cooling system',
          'Gaming/app performance: ensure latest GPU drivers installed. Check power plan is High Performance (not Balanced or Power Saver)',
        ],
      },
    ],
  },
  {
    id: 'storage-disk-issues',
    title: 'Storage & Disk Issues',
    icon: '💾',
    color: 'purple',
    sections: [
      {
        heading: 'Overview',
        content:
          'Disk issues range from logical corruption (fixable with CHKDSK and SFC) to physical SMART failures (requiring immediate backup and replacement). Windows includes CHKDSK for file system errors, SFC for Windows system file corruption, and DISM for repairing the Windows component store. For SSDs, TRIM optimization maintains performance. Monitor SMART attributes with CrystalDiskInfo (free). Any SMART warning or reallocated sector count above 0 should be treated as an urgent backup trigger.',
      },
      {
        heading: 'Disk Diagnostic Commands',
        items: [
          { label: 'Check disk for errors (schedule for next reboot)', path: 'chkdsk C: /f /r /x — /f fixes errors, /r locates bad sectors, /x dismounts volume first' },
          { label: 'CHKDSK read-only check (no changes)', path: 'chkdsk C:' },
          { label: 'System File Checker (repair Windows files)', path: 'sfc /scannow — must run as Administrator' },
          { label: 'DISM repair Windows component store', path: 'DISM /Online /Cleanup-Image /RestoreHealth' },
          { label: 'DISM check image health only', path: 'DISM /Online /Cleanup-Image /CheckHealth' },
          { label: 'DISM scan image health', path: 'DISM /Online /Cleanup-Image /ScanHealth' },
          { label: 'Check SMART health (PowerShell)', path: 'Get-PhysicalDisk | Select-Object FriendlyName, HealthStatus, OperationalStatus, Usage' },
          { label: 'List disk drives with health status (WMIC)', path: 'wmic diskdrive get model, serialnumber, status, size' },
          { label: 'Optimize (defrag HDD / TRIM SSD)', path: 'defrag C: /U /V — /U shows progress, /V verbose. Windows auto-detects SSD and runs TRIM instead of defrag' },
          { label: 'Analyze disk for fragmentation (HDD only)', path: 'defrag C: /A /U' },
          { label: 'List disk partitions (DiskPart)', path: 'diskpart then list disk then select disk 0 then list partition' },
          { label: 'Disk cleanup wizard', path: 'cleanmgr — launch Disk Cleanup for selected drive' },
          { label: 'Advanced disk cleanup including system files', path: 'cleanmgr /sageset:1 then cleanmgr /sagerun:1' },
          { label: 'Find largest files on disk (PowerShell)', path: 'Get-ChildItem C:\\ -Recurse -ErrorAction SilentlyContinue | Sort-Object Length -Descending | Select-Object -First 20 FullName, @{N="MB";E={[math]::Round($_.Length/1MB,2)}}' },
        ],
      },
      {
        heading: 'CHKDSK and SFC Procedures',
        steps: [
          'Run CHKDSK as Administrator on a non-system drive: chkdsk D: /f /r — runs immediately on non-OS drives',
          'For C: (OS drive): chkdsk C: /f /r → Windows says it will run on next restart → Type Y → Reboot',
          'CHKDSK can take 1-8+ hours on large HDDs — do not interrupt. If power fails during CHKDSK, rerun it',
          'After CHKDSK: view results in Event Viewer → Windows Logs → Application → Source: Wininit → Event ID 26212',
          'If CHKDSK finds and fixes errors: run SFC /scannow next to repair any Windows files that were affected',
          'SFC /scannow: opens CMD as Admin → sfc /scannow → wait for 100% completion (5-30 minutes)',
          'SFC results: "Windows Resource Protection did not find any integrity violations" = all good. "Found corrupt files and successfully repaired them" = fixed. "Found corrupt files but was unable to fix some" = run DISM next',
          'DISM RestoreHealth: DISM /Online /Cleanup-Image /RestoreHealth — downloads and replaces corrupted Windows components (requires internet)',
          'After DISM: run SFC /scannow again — should now repair previously unfixable files',
          'Reboot after all repair operations complete',
        ],
      },
      {
        heading: 'SMART Failure Signs and Disk Full Resolution',
        steps: [
          'Download CrystalDiskInfo (crystalmark.info/en/software/crystaldiskinfo) — free, portable, reads SMART attributes',
          'Critical SMART attributes to watch: Reallocated Sectors Count (ID 05), Pending Sectors (ID C5), Uncorrectable Sectors (ID C6). Any value above 0 = disk has bad sectors — back up immediately',
          'CrystalDiskInfo health status: Good = OK, Caution = monitoring required, Bad = replace immediately',
          'If disk shows Caution or Bad: immediately run: robocopy C:\\ D:\\Backup /E /COPYALL /R:1 /W:1 to backup all data to another drive',
          'Disk full resolution — find large files: Settings → System → Storage → Storage Sense → see breakdown by category',
          'Run Disk Cleanup: cleanmgr → tick all boxes including "Windows Update Cleanup" and "Previous Windows installations"',
          'Large temp files: Win+R → %temp% → Ctrl+A → Delete (skip files in use)',
          'Windows update files: C:\\Windows\\SoftwareDistribution\\Download — can be cleared after updates complete. Run: net stop wuauserv then delete folder contents then net start wuauserv',
          'Windows.old folder after upgrade: Disk Cleanup → Clean up system files → Previous Windows installations → check the box → OK',
          'WinSxS folder (appears huge but deduped): DISM /Online /Cleanup-Image /StartComponentCleanup /ResetBase — safely removes old component versions',
        ],
      },
      {
        heading: 'Partition Management',
        steps: [
          'Open Disk Management: Win+X → Disk Management  OR  diskmgmt.msc',
          'Extend partition: right-click volume → Extend Volume → follow wizard (requires unallocated space to the right of the partition)',
          'Shrink partition: right-click volume → Shrink Volume → enter amount to shrink in MB',
          'Create new partition: right-click Unallocated space → New Simple Volume → follow wizard',
          'Change drive letter: right-click volume → Change Drive Letter and Paths → Change → select new letter',
          'Format drive: right-click volume → Format → NTFS (Windows), exFAT (cross-platform), FAT32 (legacy) → set allocation unit size (default 4096 for general use)',
          'DiskPart for advanced operations: Run cmd as Admin → diskpart → list disk → select disk # → list partition',
          'DiskPart create partition: select disk 1 → create partition primary size=51200 → format fs=ntfs quick → assign letter=E',
          'Warning: DiskPart operations are immediate and irreversible — verify disk number carefully before destructive commands',
        ],
      },
    ],
  },
  {
    id: 'printer-setup-troubleshooting',
    title: 'Printer Setup & Troubleshooting',
    icon: '🖨️',
    color: 'green',
    sections: [
      {
        heading: 'Overview',
        content:
          'Printer issues on Windows 10/11 typically involve driver conflicts, print spooler corruption, network connectivity (for IP and shared printers), or authentication (for domain-shared printers). The print spooler service manages all print jobs — restarting it resolves a significant percentage of printing problems. For IP printers, verify the printer IP and that TCP port 9100 (raw) or 631 (IPP) is accessible. Always match driver language (PCL vs PostScript) to printer capability.',
      },
      {
        heading: 'Printer Management Commands',
        items: [
          { label: 'Open Printers & Scanners settings', path: 'Settings → Bluetooth & devices → Printers & scanners  OR  ms-settings:printers' },
          { label: 'Open legacy Devices and Printers', path: 'control printers' },
          { label: 'Restart Print Spooler service', path: 'net stop spooler && net start spooler  (run as Admin)' },
          { label: 'Clear print queue (kill spooler, delete jobs, restart)', path: 'net stop spooler && del /Q /F /S "%systemroot%\\System32\\spool\\PRINTERS\\*.*" && net start spooler' },
          { label: 'List installed printers (PowerShell)', path: 'Get-Printer | Select-Object Name, DriverName, PortName, Shared, Published' },
          { label: 'Add TCP/IP printer port (PowerShell)', path: 'Add-PrinterPort -Name "IP_192.168.1.100" -PrinterHostAddress "192.168.1.100"' },
          { label: 'Install printer with driver (PowerShell)', path: 'Add-Printer -Name "Office Printer" -DriverName "HP Universal Printing PCL 6" -PortName "IP_192.168.1.100"' },
          { label: 'Remove a printer (PowerShell)', path: 'Remove-Printer -Name "Old Printer Name"' },
          { label: 'Test TCP connection to printer port 9100 (PowerShell)', path: 'Test-NetConnection -ComputerName 192.168.1.100 -Port 9100' },
          { label: 'Test IPP connection (port 631)', path: 'Test-NetConnection -ComputerName 192.168.1.100 -Port 631' },
          { label: 'View spooler events in Event Log', path: 'Get-EventLog -LogName System -Source "Print Spooler" -Newest 20 | Select-Object TimeGenerated, EventID, Message' },
        ],
      },
      {
        heading: 'Installing and Configuring Network Printers',
        steps: [
          'IP Printer setup: Settings → Bluetooth & devices → Printers & scanners → Add device → wait for auto-discovery, or click "Add manually"',
          'Manual IP printer: Add printer that isn\'t listed → Add a printer using a TCP/IP address or hostname → enter IP → Windows will attempt auto-detection',
          'If auto-detection fails: select device type = TCP/IP Device, port name = IP_<printer IP> → Next → select printer manufacturer and model from list',
          'Download driver from manufacturer if not in Windows list: HP (support.hp.com), Canon (usa.canon.com/support), Xerox (support.xerox.com) — search by model number',
          'Universal drivers: HP Universal Print Driver PCL 6 or PS covers most HP printers. Xerox Global Print Driver similarly',
          'PCL vs PostScript: PCL (Printer Command Language) = faster, works with most apps, occasional formatting issues. PostScript = better for design/PDF accuracy, required by some workflows',
          'Shared printer from print server: Settings → Printers & scanners → Add device → select from list, or enter: \\\\servername\\printername in Run dialog (Win+R)',
          'Map shared printer via UNC path: Win+R → \\\\192.168.1.200\\HP-LaserJet → Enter → Windows connects and installs driver from server',
        ],
      },
      {
        heading: 'Print Spooler Reset and Queue Clearing',
        steps: [
          'Symptom: printer shows as offline, jobs stuck in queue, or error printing — print spooler reset resolves most cases',
          'Step 1: Open CMD as Administrator (Win+X → Windows Terminal (Admin))',
          'Step 2: Stop spooler: net stop spooler',
          'Step 3: Delete stuck jobs: del /Q /F /S "%systemroot%\\System32\\spool\\PRINTERS\\*.*"',
          'Step 4: Restart spooler: net start spooler',
          'Step 5: Try printing again. If still failing, check printer status — right-click printer → See what\'s printing → Printer menu → Cancel all documents',
          'If spooler crashes repeatedly: Event Viewer → Windows Logs → System → filter Source: Print Spooler — note the error. Third-party printer monitoring software or a corrupt driver often causes spooler crashes',
          'Fix corrupt print driver: Devices and Printers → right-click printer → Printer properties → Advanced tab → New Driver → install fresh driver',
          'Printer driver store cleanup: printmanagement.msc → Drivers → right-click old/duplicate drivers → Delete',
        ],
      },
      {
        heading: 'Fixing Printer Offline and Windows Cannot Connect',
        steps: [
          'Printer shows Offline: right-click printer → See what\'s printing → Printer menu → Uncheck "Use Printer Offline"',
          'Set as default printer: Settings → Printers & scanners → turn off "Let Windows manage my default printer" → select printer → Set as default',
          'For IP printer offline: verify IP address has not changed (check printer LCD or print a test/config page from printer). Update port IP: Printers → right-click → Printer properties → Ports tab → Configure port → update IP',
          'If printer IP keeps changing: set static IP on printer (printer web interface, typically at its current IP in browser) or create DHCP reservation in router by printer MAC address',
          '"Windows Cannot Connect to the Printer" for shared printer: verify the sharing PC is online, sharing is enabled, and firewall allows File and Printer Sharing',
          'Sharing firewall: on printer host PC: Control Panel → Windows Defender Firewall → Allow an app → ensure "File and Printer Sharing" is checked for Private networks',
          'Authentication error on shared printer: this occurs when accounts don\'t match. On host PC: right-click shared printer → Printer properties → Security → add the connecting user\'s account with Print permission',
          'Driver mismatch on shared printer: the host PC must have both 32-bit and 64-bit drivers if supporting both client types. Printer properties → Sharing → Additional Drivers → add x86 drivers for 32-bit clients',
        ],
      },
    ],
  },
  {
    id: 'display-monitor-issues',
    title: 'Display & Monitor Issues',
    icon: '🖥️',
    color: 'amber',
    sections: [
      {
        heading: 'Overview',
        content:
          'Display issues on Windows 10/11 include resolution and scaling problems (particularly with High-DPI displays), refresh rate limitations, multi-monitor configuration issues, driver crashes (black screen, artifacts), and physical connection problems. The display driver (GPU driver) is the most common cause of display issues. DDU (Display Driver Uninstaller) cleanly removes old drivers before installing fresh ones. Windows has recovered from display driver crash if you see the notification "Display driver stopped responding and has recovered".',
      },
      {
        heading: 'Display Diagnostic Commands',
        items: [
          { label: 'Open Display Settings', path: 'Settings → System → Display  OR  right-click desktop → Display settings' },
          { label: 'Open Advanced Display Settings (refresh rate)', path: 'Settings → System → Display → Advanced display' },
          { label: 'Open Screen Resolution (classic)', path: 'desk.cpl' },
          { label: 'Open Color Calibration wizard', path: 'dccw' },
          { label: 'Open Color Management', path: 'colorcpl' },
          { label: 'Open DirectX Diagnostic (GPU info)', path: 'dxdiag — check Display tab for GPU name, VRAM, driver version, feature levels' },
          { label: 'Check GPU driver version (PowerShell)', path: 'Get-WmiObject Win32_VideoController | Select-Object Name, DriverVersion, VideoModeDescription, AdapterRAM' },
          { label: 'List all display outputs (PowerShell)', path: 'Get-PnpDevice -Class Display | Select-Object FriendlyName, Status, InstanceId' },
          { label: 'Reset display driver (keyboard shortcut)', path: 'Win+Ctrl+Shift+B — resets display driver without rebooting (screen briefly goes black)' },
          { label: 'Detect additional monitors', path: 'Settings → System → Display → Multiple displays → Detect' },
          { label: 'View GPU memory and usage (Task Manager)', path: 'Task Manager → Performance → GPU — shows GPU utilization, memory, temperature' },
        ],
      },
      {
        heading: 'Resolution, Scaling, and Refresh Rate',
        steps: [
          'Set native resolution: Settings → System → Display → Display resolution — use the resolution marked "(Recommended)" which matches the monitor\'s native resolution',
          'If native resolution is not listed: update GPU driver. Outdated drivers may not detect monitor capabilities properly',
          'High-DPI scaling: for 4K or QHD monitors, set Display scale to 125% or 150% for readability. Settings → Display → Scale',
          'Per-app scaling (blurry apps): right-click app shortcut → Properties → Compatibility → Change high DPI settings → Override high DPI scaling behavior → Application',
          'Set refresh rate: Settings → System → Display → Advanced display → "Choose a refresh rate" — select maximum supported by monitor (60Hz, 75Hz, 144Hz, etc.)',
          'If max refresh rate not showing: check DisplayPort/HDMI cable version (HDMI 2.0 required for 4K@60Hz, DisplayPort 1.4 for 4K@144Hz)',
          'HDMI limitations: HDMI 1.4 = 4K@30Hz max. HDMI 2.0 = 4K@60Hz. HDMI 2.1 = 4K@120Hz+ or 8K@60Hz. Use DisplayPort for high refresh rates when possible',
          'Monitor not recognized: unplug and replug cable, try different cable, try different port on GPU, then update GPU drivers',
        ],
      },
      {
        heading: 'Multiple Monitor Configuration',
        steps: [
          'Connect second monitor and press Win+P: choose Duplicate (same on both), Extend (different content), Second screen only, or PC screen only',
          'Arrange monitors: Settings → Display → scroll down → drag monitor icons to match physical layout (so mouse moves correctly between screens)',
          'Set primary monitor: Settings → Display → select monitor → scroll down → check "Make this my main display"',
          'Different refresh rates on multi-monitor: each display should run at its own native refresh rate — Windows 10 Creators Update (1703+) supports per-monitor refresh rates',
          'Taskbar on all monitors: Settings → System → Taskbar → Taskbar behaviors → Show my taskbar on all displays',
          'Display not detected on second port: check GPU supports simultaneous outputs — some GPUs limit active display outputs. Check GPU manufacturer specs',
          'Mixed scaling (one 4K + one 1080p): Settings → Display → select each monitor separately and set appropriate scaling (200% for 4K, 100% for 1080p)',
          'If apps jump between monitors with wrong size: set all monitors to same DPI scaling (100% or 125%) to avoid scaling artifacts',
        ],
      },
      {
        heading: 'GPU Driver Issues and DDU Clean Install',
        steps: [
          'Symptom of driver issues: display artifacts (colored blocks, flickering), black screen on wake, BSOD with DRIVER_IRQL error, "Display driver stopped responding" notifications',
          'Quick fix: Win+Ctrl+Shift+B — resets GPU driver in-place without reboot. Screen goes black briefly then returns',
          'Update GPU driver: NVIDIA → GeForce Experience or nvidia.com/drivers. AMD → Radeon Software or amd.com/drivers. Intel → intel.com/support/detect',
          'Clean GPU driver install with DDU: download Display Driver Uninstaller from guru3d.com/files/details/display-driver-uninstaller-download.html',
          'DDU procedure: boot Windows into Safe Mode (Settings → Recovery → Advanced startup → Troubleshoot → Advanced options → Startup Settings → Restart → F4)',
          'In Safe Mode: run DDU → select GPU type (NVIDIA/AMD/Intel) → Clean and restart',
          'After restart (normal mode): install fresh GPU driver downloaded from manufacturer',
          'DDU is the gold standard for resolving driver conflicts, ghost driver entries, and corrupted driver installations',
          'NVIDIA: in driver installer, select "Custom installation" → check "Perform clean installation" — removes old driver data before installing',
          'After driver install: verify in dxdiag → Display tab that driver version matches installed driver',
        ],
      },
      {
        heading: 'HDMI, DisplayPort, and Color Calibration',
        steps: [
          'No signal on HDMI: ensure monitor input is set to correct HDMI port. Try different cable (HDMI cables can fail). Test cable on another device',
          'HDCP errors (streaming apps show black screen): HDMI cable must support HDCP 2.2 for 4K content. Replace cable or use certified HDMI 2.0 cable',
          'DisplayPort no signal: DisplayPort cables have a latching connector — push firmly until it clicks. Underpowered cables cause intermittent signal loss at high resolutions',
          'DisplayPort over USB-C/Thunderbolt: ensure USB-C cable supports DisplayPort Alt Mode (not all USB-C cables do)',
          'Color calibration: Settings → Display → Color profile → Color calibration — or run dccw for wizard',
          'For accurate color (design/photo work): download ICC profile from monitor manufacturer and install: right-click .icm file → Install Profile, then set in Color Management (colorcpl)',
          'Night light (reduce blue light): Settings → Display → Night light — schedule or manual, adjust color temperature',
          'HDR enabling: Settings → Display → HDR — only enable if monitor supports HDR (HDR600, VESA DisplayHDR certified). Enabling HDR on non-HDR monitors washes out colors',
        ],
      },
    ],
  },
  {
    id: 'bios-uefi-boot-issues',
    title: 'BIOS/UEFI & Boot Issues',
    icon: '⚙️',
    color: 'cyan',
    sections: [
      {
        heading: 'Overview',
        content:
          'BIOS/UEFI issues affect the lowest level of PC operation: boot order, Secure Boot, hardware initialization, and pre-OS firmware settings. Boot problems manifest as "no bootable device," black screen after POST, boot loop, or Windows recovery mode. Windows 10/11 includes boot repair tools: bootrec.exe (MBR/BCD repair) and Startup Repair in Recovery Environment. Understanding UEFI vs Legacy (MBR vs GPT) is essential for correct boot configuration, especially after disk replacement or fresh Windows installations.',
      },
      {
        heading: 'BIOS Access Keys by Manufacturer',
        items: [
          { label: 'Dell (most models)', path: 'Press F2 repeatedly at Dell logo during POST' },
          { label: 'HP (consumer — ProBook/EliteBook)', path: 'Press F10 at HP logo  OR  Esc then F10 for Setup' },
          { label: 'Lenovo (ThinkPad)', path: 'Press F1 during boot  OR  Fn+F1 on some models' },
          { label: 'Lenovo (IdeaPad/consumer)', path: 'Press F2 or Fn+F2 at Lenovo logo' },
          { label: 'ASUS', path: 'Press Delete or F2 at ASUS logo' },
          { label: 'MSI', path: 'Press Delete at MSI logo' },
          { label: 'Gigabyte', path: 'Press Delete at startup' },
          { label: 'Surface (Microsoft)', path: 'Hold Volume Up + press Power → UEFI opens' },
          { label: 'Access BIOS from within Windows 11', path: 'Settings → System → Recovery → Advanced startup → Restart now → Troubleshoot → Advanced options → UEFI Firmware Settings → Restart' },
          { label: 'Force boot menu (one-time boot device)', path: 'Dell: F12  |  HP: F9 or Esc  |  Lenovo: F12  |  ASUS: F8  |  Press at startup' },
        ],
      },
      {
        heading: 'Secure Boot and Boot Order Configuration',
        steps: [
          'Secure Boot: BIOS → Security or Boot tab → Secure Boot → Enabled (required for Windows 11 TPM 2.0 requirement)',
          'Windows 11 requires Secure Boot ON and TPM 2.0. Check: Win+R → tpm.msc → verify TPM status',
          'Disable Secure Boot temporarily (for Linux dual-boot or legacy OS): BIOS → Security → Secure Boot → Disabled. Note: re-enable after use for security',
          'Some BIOS require clearing Secure Boot keys to switch from UEFI to Legacy: Platform Key (PK) must be cleared to enter Setup Mode',
          'Boot order: BIOS → Boot tab → Boot Priority → drag or use +/- keys to set: SSD/NVMe → then optical drive → then USB',
          'UEFI vs Legacy (CSM): modern Windows 10/11 on GPT disk requires UEFI mode. Legacy BIOS mode uses MBR partition scheme. Mixing them causes boot failures',
          'Check Windows boot mode: msinfo32 → BIOS Mode: shows UEFI or Legacy. Disk partition style: Disk Management → right-click disk → Properties → Volumes → Partition style: GPT (UEFI) or MBR (Legacy)',
          'Fast Boot: BIOS option that skips hardware initialization checks. Can prevent USB drives from being detected and cause intermittent boot issues — disable for troubleshooting',
        ],
      },
      {
        heading: 'Windows Boot Repair (bootrec and WinRE)',
        steps: [
          'Boot from Windows installation USB: press BIOS boot key (F12/F8/Esc) → boot from USB → choose language → Repair your computer (bottom left)',
          'Windows Recovery Environment: Troubleshoot → Advanced options → Command Prompt',
          'Repair MBR: bootrec /fixmbr — rewrites master boot record (for MBR/Legacy boot)',
          'Repair boot sector: bootrec /fixboot — writes new boot sector to system partition',
          'Rebuild BCD (Boot Configuration Data): bootrec /rebuildbcd — scans for Windows installations and rebuilds boot menu',
          'Full repair sequence: bootrec /fixmbr → bootrec /fixboot → bootrec /scanos → bootrec /rebuildbcd → restart',
          'For UEFI/GPT systems: use bcdboot instead: bcdboot C:\\Windows /s S: /f UEFI (where S: is the EFI partition — assign it a letter first: diskpart → select disk 0 → list partition → select partition 1 → assign letter=S)',
          'Startup Repair (automatic): WinRE → Troubleshoot → Advanced options → Startup Repair — runs automatic diagnosis and fixes common boot issues',
          'If Startup Repair fails: try System Restore: WinRE → Advanced options → System Restore → select a restore point from before the issue',
        ],
      },
      {
        heading: 'Safe Mode Access Methods',
        steps: [
          'Method 1 (from Windows login screen): hold Shift → click Power → Restart → Troubleshoot → Advanced options → Startup Settings → Restart → F4 (Safe Mode) or F5 (Safe Mode with Networking)',
          'Method 2 (from Windows Settings): Settings → System → Recovery → Advanced startup → Restart now → Troubleshoot → Advanced options → Startup Settings → Restart → F4',
          'Method 3 (msconfig — persistent): Win+R → msconfig → Boot tab → check Safe Boot → Minimal → OK → Restart. Uncheck when done',
          'Method 4 (bcdedit — persistent): bcdedit /set {default} safeboot minimal then restart. Disable: bcdedit /deletevalue {default} safeboot',
          'Method 5 (if Windows won\'t boot): interrupt startup 3 times by pressing reset/power during Windows logo → Windows enters Automatic Repair → Advanced options → Safe Mode',
          'Safe Mode with Networking: same as above but choose F5 or "Safe Mode with Networking" — allows internet access for downloading drivers or tools',
          'Use Safe Mode for: GPU driver removal (DDU), removing stubborn malware, diagnosing startup crashes, rolling back problematic drivers',
        ],
      },
    ],
  },
  {
    id: 'driver-management',
    title: 'Driver Management',
    icon: '🎮',
    color: 'purple',
    sections: [
      {
        heading: 'Overview',
        content:
          'Driver management is a critical IT support skill. Outdated, corrupted, or incompatible drivers cause BSODs, hardware malfunctions, and performance issues. Windows Update delivers some drivers but rarely the latest or most stable versions — OEM manufacturer sites always have the current drivers. For GPU drivers, always use DDU (Display Driver Uninstaller) for clean removal before installing new versions. Driver signing (WHQL certification) ensures drivers have passed Microsoft compatibility testing.',
      },
      {
        heading: 'Driver Management Commands',
        items: [
          { label: 'Open Device Manager', path: 'devmgmt.msc  OR  Win+X → Device Manager' },
          { label: 'Show all drivers including hidden', path: 'Device Manager → View → Show hidden devices' },
          { label: 'Export full driver list to text file', path: 'driverquery /fo LIST > C:\\drivers.txt' },
          { label: 'Export signed driver details', path: 'driverquery /si /fo CSV > C:\\drivers_signed.csv' },
          { label: 'Check for unsigned drivers (may cause instability)', path: 'sigverif — opens File Signature Verification tool' },
          { label: 'List all installed drivers with dates (PowerShell)', path: 'Get-WindowsDriver -Online | Sort-Object Date -Descending | Select-Object Driver, OriginalFileName, Date, Version, ProviderName | Format-Table -AutoSize' },
          { label: 'Export all driver packages (backup)', path: 'pnputil /export-driver * C:\\DriverBackup' },
          { label: 'Install a driver package manually', path: 'pnputil /add-driver C:\\driver.inf /install' },
          { label: 'Remove a driver from driver store', path: 'pnputil /delete-driver <oem#.inf> /uninstall /force' },
          { label: 'List third-party driver store packages', path: 'pnputil /enum-drivers' },
          { label: 'Open Windows Update optional updates (drivers)', path: 'Settings → Windows Update → Advanced options → Optional updates → Driver updates' },
          { label: 'View driver history (Device Manager)', path: 'Device Manager → right-click device → Properties → Driver tab → Driver Details and Roll Back Driver' },
        ],
      },
      {
        heading: 'Updating and Rolling Back Drivers',
        steps: [
          'Update via Device Manager: right-click device → Update driver → Search automatically — this searches Windows Update, not the full internet',
          'Better method: Device Manager → right-click → Update driver → Browse my computer for drivers — after downloading from OEM site',
          'Roll back driver: Device Manager → right-click device → Properties → Driver tab → Roll Back Driver (only available if a previous version was installed)',
          'Roll back is grayed out if: no previous version stored, or it is a new device. In that case, manually install older driver from OEM site',
          'Disable a driver (device): right-click → Disable device — useful for testing if a specific device causes system instability',
          'Uninstall driver: right-click → Uninstall device → check "Delete the driver software for this device" → Uninstall → reboot',
          'After uninstall reboot: Windows may reinstall a generic driver automatically from Windows Update — prevent this: Settings → Windows Update → Advanced options → Optional updates → uncheck the specific driver',
          'Prevent Windows from automatically installing specific driver: use "Show or hide updates" tool (wushowhide.diagcab) — download from Microsoft support page for your Windows version',
        ],
      },
      {
        heading: 'OEM Driver Download Sources',
        items: [
          { label: 'Dell drivers (search by Service Tag)', path: 'dell.com/support → Enter Service Tag → Drivers & Downloads → filter by category' },
          { label: 'HP drivers (search by serial or product number)', path: 'support.hp.com → Enter product → Software and Drivers → Operating System: Windows 11' },
          { label: 'Lenovo drivers (ThinkPad/IdeaPad by model)', path: 'support.lenovo.com → search model → Drivers & Software → filter by OS' },
          { label: 'ASUS drivers (motherboard, laptop)', path: 'asus.com/support → search model → Driver & Utility' },
          { label: 'NVIDIA GPU drivers', path: 'nvidia.com/drivers → select GPU series, product, OS → download Game Ready or Studio driver' },
          { label: 'AMD GPU drivers', path: 'amd.com/en/support/download/drivers.html → select GPU → Windows 11 64-bit' },
          { label: 'Intel GPU drivers (integrated)', path: 'intel.com/content/www/us/en/support/detect.html — use Driver & Support Assistant for auto-detection' },
          { label: 'Intel NIC and WiFi drivers', path: 'downloadcenter.intel.com → search adapter model (e.g., AX201, I219-V)' },
          { label: 'Realtek audio/NIC drivers', path: 'realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software' },
          { label: 'Generic chipset/inf drivers (WHQL)', path: 'catalog.update.microsoft.com → search device ID from Device Manager → download WHQL-certified package' },
        ],
      },
      {
        heading: 'DDU Clean Driver Install Procedure',
        steps: [
          'Download DDU from guru3d.com — do not run from within a normal Windows session for GPU drivers',
          'Download new GPU driver from NVIDIA, AMD, or Intel BEFORE starting the DDU process (store on desktop or USB)',
          'Boot into Safe Mode: Settings → Recovery → Advanced startup → Restart → Troubleshoot → Advanced options → Startup Settings → F4',
          'In Safe Mode: run DDU → Select device type (GPU) → Select device (NVIDIA/AMD/Intel) → Clean and restart',
          'On restart (in normal Windows): install the new GPU driver downloaded earlier',
          'NVIDIA: choose Custom installation → check "Perform clean installation"',
          'AMD: in installer, select Custom → check "Factory Reset"',
          'After installation: verify with dxdiag → Display tab — confirm new driver version and date',
          'DDU also works for audio drivers, NIC drivers, and other device types — use when standard driver update leaves corrupt remnants',
          'Driver signing: unsigned drivers on 64-bit Windows will not load by default. Install only WHQL-signed drivers from manufacturer sites. sigverif tool identifies unsigned drivers in the system',
        ],
      },
      {
        heading: 'BSOD Driver-Related Stop Codes',
        steps: [
          'SYSTEM_THREAD_EXCEPTION_NOT_HANDLED: usually a driver file listed in the error (e.g., nvlddmkm.sys for NVIDIA). Update or rollback that driver',
          'IRQL_NOT_LESS_OR_EQUAL: memory addressing error, often caused by NIC, GPU, or USB driver. Run Windows Memory Diagnostic to rule out RAM. Then update drivers',
          'PAGE_FAULT_IN_NONPAGED_AREA: corrupted driver or RAM issue. Identify faulting module from crash dump in Event Viewer → Windows Logs → System → Event ID 1001',
          'VIDEO_TDR_FAILURE (atikmpag.sys or nvlddmkm.sys): GPU driver timeout. Run DDU and clean install latest GPU driver',
          'DRIVER_IRQL_NOT_LESS_OR_EQUAL: network adapter driver common cause. Update NIC driver or disable advanced NIC features (RSS, VMQ, Offloads)',
          'Read mini crash dumps: C:\\Windows\\Minidump\\ — open with WinDbg (from Microsoft Store) or analyze online at osronline.com for the faulting driver',
          'Windows Error Reporting: Event Viewer → Windows Logs → Application → Source: Windows Error Reporting — contains module names and fault offsets for driver crashes',
        ],
      },
    ],
  },
]

export default function HardwarePage() {
  return (
    <>
      <TopBar
        title="Hardware & Network Guide"
        subtitle="Windows diagnostics, network troubleshooting, hardware fixes"
      />
      <div className="flex-1 p-6 grid-bg overflow-y-auto">
        <div className="max-w-4xl mx-auto">
          <DocSection sections={HARDWARE_DOCS} />
        </div>
      </div>
    </>
  )
}
